README.md

* We don't have runtime permissions.
* We don't have privacy concerns for now.
* List of available libraries is not useful.

Remove end of document

---

codecov.yml
sdk/mobile-center-crashes/src/androidTest/java/com/microsoft/azure/mobile/crashes/WrapperSdkExceptionManagerAndroidTest.java
sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/WrapperSdkExceptionManager.java
sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/ingestion/models/Exception.java
sdk/mobile-center-crashes/src/test/java/com/microsoft/azure/mobile/crashes/CrashesTest.java
sdk/mobile-center-crashes/src/test/java/com/microsoft/azure/mobile/crashes/WrapperSdkExceptionManagerTest.java

* Fix a file leak when data could not be read.
* Fix noisy logging when wrapper sdk not used.
* Fix unit tests.

Fix issues wrapper sdk exception manager

---

sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/model/ErrorAttachment.java

When using only a binary attachment.

Fix empty string being serialized as text attachment

---

apps/sasquatch/src/main/AndroidManifest.xml
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/CrashActivity.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/ManagedErrorActivity.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/features/TestFeatures.java
apps/sasquatch/src/main/res/layout/activity_list.xml
apps/sasquatch/src/main/res/values/crashes.xml
apps/sasquatch/src/main/res/values/strings.xml
sdk/mobile-center-crashes/src/androidTest/java/com/microsoft/azure/mobile/crashes/CrashesAndroidTest.java
sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/utils/ErrorLogHelper.java

Keep 128 first frames and 128 last frames for huge exceptions.
Add that test in sasquatch and integration test.

Truncate stack overflow error to avoid app from crashing forever

---

apps/sasquatch/src/jcenterDependency/java/com/microsoft/azure/mobile/analytics/mobile/sasquatch/features/GetLastSessionErrorReportFeatureTest.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/MainActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/azure/mobile/analytics/mobile/sasquatch/features/GetLastSessionErrorReportFeatureTest.java
sdk/mobile-center-crashes/src/androidTest/java/com/microsoft/azure/mobile/crashes/CrashesAndroidTest.java
sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/Crashes.java
sdk/mobile-center-crashes/src/test/java/com/microsoft/azure/mobile/crashes/CrashesTest.java

The sync version is no longer available as a public method, and the async method loses its suffix.

Team decided to do a breaking change in getErrorReport

---

sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/Crashes.java
sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/UncaughtExceptionHandler.java
sdk/mobile-center-crashes/src/test/java/com/microsoft/azure/mobile/crashes/UncaughtExceptionHandlerTest.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/MobileCenter.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/utils/ShutdownHelper.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/MobileCenterTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/utils/ShutdownHelperTest.java

Shutdown channel on uncaught exception moved form Crashes module to core.
It's important in case when Crashes module not used in user application.
- Remembering the previous uncaught exception handler for chain handlers
- Move ShutdownHelper class to core utils to not duplicate code
- Added unit tests for UncaughtExceptionHandler
- Added unit tests for ShutdownHelperTest
- Fixed comments style in UncaughtExceptionHandlerTest.java

Shutdown channel on uncaught exception without Crashes module

---

sdk/mobile-center/src/androidTest/java/com/microsoft/azure/mobile/ingestion/http/HttpUtilsAndroidTest.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/ingestion/http/HttpUtils.java

The error like 
```
java.io.IOException: unexpected end of stream
...
Caused by: java.io.EOFException: \n not found
```
should be retryable, but before not detected as it.

Add exception cause check to improve recoverable detection

---

sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/CheckDownloadTask.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/Distribute.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/AbstractDistributeTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeMandatoryDownloadTest.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/channel/DefaultChannel.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/channel/AbstractDefaultChannelTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/channel/DefaultChannelRaceConditionTest.java

Without this PR we can randomly get this crash on API level 15:
```
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to pause activity {com.microsoft.azure.mobile.sasquatch.jcenter/com.microsoft.azure.mobile.sasquatch.activities.MainActivity}: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2706)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2662)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2640)
at android.app.ActivityThread.access$800(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1154)
at …
```

Fix issues with AsyncTask.onPostExecute being called in wrong thread

---

sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/CheckDownloadTask.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/Distribute.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/AbstractDistributeAfterDownloadTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/AbstractDistributeTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeHttpTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeMandatoryDownloadTest.java

* If receiving completion callback and updating progress at the same time.
* If application exits while processing completion callback.

Fix 2 scenarios where progress dialog can be stuck at 100%

---

sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/Distribute.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeBeforeDownloadTest.java

When clicking on download after restarting offline
then going online and while still in app.

Fix duplicate update dialog with offline cache

---

apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
sdk/build.gradle
sdk/mobile-center-push/build.gradle
sdk/mobile-center-push/src/main/java/com/microsoft/azure/mobile/push/FirebaseAnalyticsUtils.java
sdk/mobile-center-push/src/main/java/com/microsoft/azure/mobile/push/Push.java
sdk/mobile-center-push/src/test/java/com/microsoft/azure/mobile/push/PushTest.java

Firebase Analytics is disabled by default, and only after user calls enableFirebaseAnalytics it is enabled

enableFirebaseAnalytics method added to Push module 

---

apps/sasquatch/src/androidTest/java/com/microsoft/azure/mobile/sasquatch/activities/AnalyticsTest.java
apps/sasquatch/src/androidTest/java/com/microsoft/azure/mobile/sasquatch/activities/CrashesTest.java
apps/sasquatch/src/androidTest/java/com/microsoft/azure/mobile/sasquatch/activities/SettingsActivityTest.java
apps/sasquatch/src/androidTest/java/com/microsoft/azure/mobile/sasquatch/activities/utils/EspressoUtils.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/crashes/CrashesPrivateHelper.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/CrashActivity.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/res/values/crashes.xml

We can't truly restart application in tests, so my solution is save handled exception info after crash happened, reset mobile center singletons and restart activity.
Also, some kind of crashes can't be tested by this method.

Add crashes UI tests

---

apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/MainActivity.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/http/DefaultHttpClient.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/http/DefaultHttpClientTest.java

With the new strict mode line and without the http patch you would see:
```
05-08 18:26:36.692 10407-10416/com.microsoft.azure.mobile.sasquatch.project E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at java.util.zip.Inflater.<init>(Inflater.java:104)
at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
at …
```

Fixed http response leak

---

sdk/mobile-center-analytics/src/androidTest/java/com/microsoft/azure/mobile/analytics/AnalyticsAndroidTest.java
sdk/mobile-center-crashes/src/androidTest/java/com/microsoft/azure/mobile/crashes/CrashesAndroidTest.java
sdk/mobile-center-crashes/src/androidTest/java/com/microsoft/azure/mobile/crashes/WrapperSdkExceptionManagerAndroidTest.java
sdk/mobile-center-crashes/src/test/java/com/microsoft/azure/mobile/crashes/UncaughtExceptionHandlerTest.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/AbstractMobileCenterService.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/MobileCenter.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/AbstractMobileCenterServiceTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/MobileCenterTest.java

This returns false and prints an error now.

Fix a crash when calling AnyService.isEnabled() before start

---

sdk/build.gradle
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/Distribute.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/InstallerUtils.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeWarnUnknownSourcesTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/UnknownSourcesDetectionTest.java

> Starting from O, apps should use canRequestPackageInstalls()
https://developer.android.com/reference/android/provider/Settings.Secure.html#INSTALL_NON_MARKET_APPS

Use PackageManager.canRequestPackageInstalls() on Android O

---

sdk/mobile-center-distribute/src/androidTest/java/com/microsoft/azure/mobile/distribute/BrowserUtilsTest.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/BrowserUtils.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/DeepLinkActivity.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/Distribute.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/DistributeConstants.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/DistributeUtils.java
sdk/mobile-center-distribute/src/main/res/values/mobile_center_distribute.xml
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DeepLinkActivityTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeBeforeApiSuccessTest.java

The aim of this PR is to bring the similar functionality as was currently created at iOS SDK: https://github.com/Microsoft/mobile-center-sdk-ios/pull/773.
Any feedback and remarks are much appreciated.

Only show in-app update failure message once per release

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AbstractAppCenterService.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java

In a case when `AppCenter` is disabled, but some service is enabled, `applyEnabledState(true)` was called.
It's causing some issues, for example, rum sending network requests while `AppCenter` is disabled.

Disable services if AppCenter is disabled 

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/channel/DistributeInfoTracker.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeAfterDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/channel/DistributeInfoTrackerTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/AbstractLog.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/Log.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/AbstractLogTest.java

This PR:
- Adds `distributionGroupId` field to sent logs (if exists).
- Adds a channel listener in the Distribution module which sets the `distributionGroupId` value.

Add tracking of the distribution group ID to Analytics

---

sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeAfterDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/channel/DistributeInfoTrackerTest.java

This PR fixes warnings related to unused imports and the variables to be inlined in appcenter-distribute tests.

Remove unused imports/variables from appcenter-distribute tests

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DeepLinkActivity.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeConstants.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DeepLinkActivityTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java

Apps installed using the native tester app currently aren't able to successfully enable in-app updates, because the cookies stored on install aren't there. This is part of the work to fix that.
When enabling in-app updates, the Android SDK should check if an app with the ms-actesterapp:// scheme (belongs to the App Center tester app) is installed. If it is, then it should try to enable in-app updates by redirecting to that scheme instead of the update-setup page on the install portal. If for some reason enabling in-app updates fails, then the SDK should fall back to attempting to enable in-app updates using the update-setup page. This could happen if someone has the native tester app installed, but for some reason they still install an app from the install portal. The user will see two …

use tester app to enable in-app updates if it’s installed

---

sdk/appcenter-distribute/src/androidTest/java/com/microsoft/appcenter/distribute/DistributeSerializerTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ingestion/models/DistributionStartSessionLog.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ingestion/models/json/DistributionStartSessionLogFactory.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/ingestion/models/DistributionStartSessionLogTest.java

This PR addresses the issue with the first session log which is sent after app installation. The `distributionGroupId` field is missing in the first session log because it's sent before in-app updates are enabled. So this PR:
- Adds sending of distribution start session log after enabling in-app updates (first app launch after installation).
- Adds check to ignore distribution start session logs without session ID to handle cases when Analytics is disabled.
- Implements tests.

Log the missing `distributionGroupId` for the first session

---

sdk/appcenter-distribute/src/androidTest/java/com/microsoft/appcenter/distribute/ReleaseDetailsTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/CheckDownloadTask.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeConstants.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDetails.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeDownloadTest.java

This PR implements updating of distribution group ID if in-app updated release has different distribution group.
Group ID may change if one user is added to different distribution groups and a new release was distributed to another group.

Update distribution group ID if new ID is sent in the latest release details

---

build.gradle

* verified it does not break the two build configurations in our CI
* verified building the test app in app center works

Bump version of gradle bintray plugin to 1.8.0

---

sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/AbstractCrashesListener.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/CrashesListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeListener.java
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/PushListener.java

Setting up a listener in ui thread incorrectly triggers a warning
of not being in a worker thread, it's just an interface but code
analysis makes wrong assumptions. It also cause the same bug vice versa
if you setup a listener from worker thread and get warnings for ui thread.
Setting up a listener is not the same as it being invoked, setting up
is allowed in any thread but code analysis not smart enough.
Plus people that don't have google annotations as a dependency can get
compiler warnings anyway so it was already established not to use
the annotations in public APIs.

Remove @UiThread and @WorkerThread from public listeners

---

sdk/appcenter/src/test/java/com/microsoft/appcenter/http/HttpClientNetworkStateHandlerTest.java

Since we verify the `cancel();` invocation, there is no need for additional stuff with threads.

Fix flacky HttpClientNetworkStateHandler tests

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
sdk/build.gradle

Reverts Microsoft/AppCenter-SDK-Android#653
Cause: cannot run tests from Android Studio.

Revert "Update jacoco, gradle and android gradle plugin versions"

---

sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/PushNotifier.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/PushNotifierTest.java

Apply big text style like Distribute and also like Firebase SDK does.

Fix notification message being truncated

---

sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java

Use a default value instead of crashing during crash saving.

Fix crash reporting when failing to get process name

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

Persistence will need to be initialized even if using only target token now with one collector transmission in core.

Make persistence mandatory again

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/AbstractChannelListener.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/Channel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/OneCollectorChannelListener.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/OneCollectorChannelListenerTest.java

Reflects design change and iOS implementation.
Removing group is specific to Android so needs to be mirrored as well in one collector groups.

 Use add/remove callbacks to manage one collector group lifecycle

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/AbstractDefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelRaceConditionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

Reported by user when calling Analytics.setEnabled(false), the timer task for batching logs can be valid from main thread when timer executes, then we post the task to trigger ingestion in another thread. Channel group can be removed before the task executes and trigger the crash.
We don't need the timer to be in main thread so the solution is to make sure every channel operation is in background thread, including the timer so that if it triggers, the disabling can happen only after. If disable happens before, then timer will be canceled.
The solution actually simplifies the code as we already had the handler for app center background thread.

Fix a crash when disabling a module at the same time logs are sent

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/OneCollectorChannelListener.java

This works since we send only events to 1 log group.
In the future we'll also need to tune the executor in http client.

Use only 2 connections max for one collector

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/array.xml
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/UncaughtExceptionHandler.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/Channel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

The feature is not 100% complete yet but we want to split in multiple PRs if possible or at least start review now before it gets too big.
What works with the feature:
* startFromLibrary before or after the app and track events.
* make sure start service log is sent after the app specifies app secret.
What does not work yet:
* Send start session log if app starts analytics after library (Fixed by #737)
* Preventing multiple calls to AppCenter.start with null appSecret. There is a pending discussion.

Introduce AppCenter.startFromLibrary

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeHttpTest.java
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/PushTest.java
sdk/appcenter-rum/src/main/java/com/microsoft/appcenter/rum/RealUserMeasurements.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/AppCenterAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AbstractAppCenterService.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenterService.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterServiceTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java

* Improve #736 
* Fixes sending start session if library starts Analytics then app starts Analytics (sent when app starts).
* Fixes automatic page tracking the same way as previous point.
* If Crashes started at app level with app secret, and Analytics started only from library, make sure we don't allow static trackEvent/trackPage calls (only AnalyticsTransmissionTarget calls are allowed for libraries).

Multitenancy: Fix start session / page tracking and static track calls behavior

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-rum/src/main/java/com/microsoft/appcenter/rum/RealUserMeasurements.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/AppCenterAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AbstractAppCenterService.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenterService.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java

It was working earlier by starting Analytics from app first.
Also renamed a parameter.

Prevent starting Push (or other modules) from library

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AbstractAnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java

First PR for nesting.
TODO: delete logs for disabled targets but this first PR can already be merged.

Nesting is/setEnabled in Analytics transmissions

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/AppExtension.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/AppExtensionTest.java

This change adds a `PropertyConfigurator` to `AnalyticsTransmissionTarget`, which is used to override common schema properties.  Properties are inherited in the same way that event properties are.

Override Common Schema Part A properties

---

apps/sasquatch/src/jcenterDependency/java/com/microsoft/appcenter/sasquatch/activities/EventPropertiesActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventPropertiesActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/EventPropertiesActivity.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java

Since they behave generally the same way as other properties, they are being moved to the `PropertyConfigurator`.

Moving set/removeEventProperty to PropertyConfigurator

---

sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

It was harmless because of internal checks.

Fix duplicate initialize call

---

sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/TokenService.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/TokenServiceTest.java

Will also be useful for an experiment to investigate an unexplained issue on Xamarin, to the very least to rule out the wrapper code as a cause.

Remove obsolete push code now that firebase is mandatory dependency

---

versions.gradle

No incidence on SDK library consumers, this mostly impacts test app.
Could not do it before as Android 9 was not supported in App Center build.

Compile/target Android 9

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/PersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/StorageHelperAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/Channel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/Persistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/StorageHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterLibraryTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterStorageTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelOtherOperationsTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/persistence/DatabasePersistenceTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/DatabaseManagerTest.java

Adding setMaxStorageSize API to core module with the following behaviors:
- Set the storage size to a given amount, in bytes, rounded up to the nearest 4KB.
- Return value is "true" if the storage size was set to the next multiple of 4kB or false otherwise.
- If the number of logs currently stored is already larger than the new storage size, the size won't be set.
- The minimum storage size allowed is 20KB (20480 bytes) (SQL limitation).
- When new logs are inserted while the storage is full, the oldest logs will be discarded until the new log fits.
- If a log is larger than the entire storage size, all logs will be removed from storage, and the new log will be discarded.  This decision was made because calculating the size of individual logs already in storage is a very expensive …

Set max storage size

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AbstractAnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java

Use the fact that any operation are queued into background looper so it is guaranteed that the `initInBackground` will be called in a sequence after the `Analytics.onStarted` that set context/channel to non null, in other terms if you execute anything in post, it will always have non null channel/context.

Fix creating a target right after AppCenter.start

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelAlternateIngestionTest.java

Previously it was working only with AppCenter logs to send pending logs after app restarted.
The if condition was wrong and the unit tests were also written the wrong way.

Fix sending previous one collector logs after app restart

---

sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactoryTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaLogSerializerTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/ExtensionsTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/MetadataExtensionTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/PartCUtilsAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/Data.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/Extensions.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/MetadataExtension.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartAUtils.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartCUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/PartAUtilsTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/PartCUtilsTest.java

Add metadata extension to common schema logs when a Part C property is not using the default JSON type.

Common schema for Analytics.trackEvent with typed properties

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java

Add strong type properties to transmission target trackEvent and fix test app.

AnalyticsTransmissionTarget.trackEvent(String, EventProperties) with strong types

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java

Test app U.I. in a separate PR.

Add strong typing to common event properties

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/CustomProperties.java

* Avoid concurrent modification exceptions while and after calling setCustomProperties by taking a snapshot of properties when we call `setCustomProperties`.
* Avoid bypassing the size limit by inserting keys from multiple threads.

Fix 2 issues related to thread safety in CustomProperties

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventPropertiesActivity.java

The event properties of transmission targets can't be removed in the test app. When added an common event property for a transmission target, then remove this property under this transmission target, and reenter Event properties page for this transmission target, observe the added event property still displayed.

Fix removing target properties UI

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactory.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactoryTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/AbstractLog.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/Log.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/AbstractLogTest.java

* Fix part A properties to not be applied retro-actively.
* Fix distinction between default target and explicit target using the same token.

Fix part A properties to not be applied retro-actively

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/PersistenceAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/Flags.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/Persistence.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/InstantiationTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelAlternateIngestionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelOtherOperationsTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelPauseResumeTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/persistence/DatabasePersistenceTest.java

Add priority field to persistence.

Add priority to database persistence

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/OneCollectorChannelListener.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaLog.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/OneCollectorChannelListenerTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/MockCommonSchemaLog.java

Add flags to common schema payload

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/CrashActivity.java
apps/sasquatch/src/main/res/values/crashes.xml
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClient.java

Preventing stack overflow crash while reading a huge throwable file.
#855

Preventing stack overflow crash while reading a huge throwable file

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java

Add flags to trackEvent that take EventProperties as a parameter.
Use Flags.DEFAULT_FLAGS for all previous signatures.

Add flags to trackEvent API

---

sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

Use mocks as in emulator it does not always fail to save a huge crash.
Use mocks as in emulator it does not always fail to save a huge crash.

Fix reliability of testing save stackoverflow bug

---

sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java

Last attempts were not enough: https://msmobilecenter.visualstudio.com/SDK/_build/results?buildId=375780&view=logs
To verify cause truncation we just need to test utility anyway.
Needed for #866

Fix test reliability of truncating causes

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java

 Add flags to AnalyticsTransmissionTarget.trackEvent(String, Map)

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

Change storage size to 32KB (don't restart)
Crash with "generate huge exceptions and a lot of causes"
Restart app and click send.
Check logs: json file deleted because putLog failed, but throwable file is still there.

Fix a bug where crash data file could leak when the database is full

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java

Set size to minimum accepted value on fresh install (20480).
Restart app => failed dialog.
SDK message: Could not change maximum database size to 20480 bytes, current maximum size is 24576 bytes.
We need to bump minimum size due to the new index.

Min database size changed with index

---

CHANGELOG.md
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/PushTest.java

1. Start Sasquatch
2. Go to settings
3. Disable push
4. Restart app
5. Go to settings
6. Enable push
7. Stay on settings screen, do not turn screen off and on
8. Push => no dialog
Reason is that `mActivity` is null in that case for Push class, we need to store/update `mActivity` reference even when Push is disabled so that it's ready at enabled time.

Fix push foreground listener after re-enabling push service

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/Constants.java

Add UserId to property configurator so UserId can be configured for transmission targets.
- #888

Add UserId to property configurator for transmission targets

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/NetworkStateHelper.java

Log was used directly in NetworkStateHelper instead of AppCenterLog.

Fix disabling network state logs when debug logs disabled

---

build.gradle

Reverts Microsoft/AppCenter-SDK-Android#907
As google fixed the google() repo.

Revert "Fix build issue"

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/ManagedErrorActivity.java

1. In the Settings Android SDK demo App Sasquatch, set Storage Max Size to 369 KB
2. Kill and restart the app, the Storage Max Size set 369 KB successfully.
3. Click back button until app exit.
4. Launch the app again, view the Storage Max Size.
The Storage Max Size should still be 369 KB
It says failed to change Storage Max Size. And Storage Max Size is set to the same as Storage file size as 24KB.

Fix test app

---

CHANGELOG.md
sdk/appcenter-distribute/src/androidTest/java/com/microsoft/appcenter/distribute/BrowserUtilsTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/BrowserUtils.java
versions.gradle

Removed the code forcing Android SDK users to open chrome before other browser. Now we will first check for the default browser and then proceed to open that. 

[Fix] Not forcing Chrome when opening a browser in distribution flow

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java

Fix exception if we receive deep link intent with setup failure before `onStart`.
#929

Fix exception if we receive deep link intent with setup failure before onStart

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/DatabaseManagerTest.java

Addition to #932

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java

Change warning to error message for cannot sign out and update wording.
Missed feedbacks last time on sign out.

Identity.SignOut: Apply code convention on instance + synchronized + post background

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppStoreDetectionTest.java

From MIUI 10, it started to return `com.miui.packageinstaller` as application package name instead of null for local installed applications. It causes the problem that in-app update stops working because it treats application as installed from a store. So, 'com.miui.packageinstaller` should be added as know local stores to identify correctly that applicaiton is not installed from a store.
Output of the app center logger with Verbose log level enabled (before fix): 
```
D/AppCenterDistribute: InstallerPackageName=com.miui.packageinstaller
I/AppCenterDistribute: Not checking in app updates as installed …
```

Fix in-app update for MIUI 10

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/res/values/env.xml
apps/sasquatch/src/projectDependency/res/values/env.xml
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeUtils.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Constants.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java

* Add Identity.setConfigUrl to change remote configuration endpoint.
* Change default value for prod.
* AB#58365

Implement Identity.setConfigUrl and change default to prod

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/AppCenterIngestion.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/Ingestion.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/OneCollectorIngestion.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/AbstractDefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelAlternateIngestionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelCallbacksTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelPauseResumeTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelRaceConditionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/AppCenterIngestionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/OneCollectorIngestionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/context/AuthTokenContextTest.java

To avoid sending incorrect token for logs we should remove `mAuthToken` from `AppCenterIngestion` and pass it as a parameter to each batch of logs on sending.
AB#58501

Delete AuthToken from AppCenterIngestion and pass it from each batch

---

sdk/appcenter-identity/build.gradle

Temporarily revert msal to 0.2.1-SNAPSHOT
0.2.2 last snapshot breaks sign in with timezone parsing error.
0.2.1 works but not on Facebook...

Temporarily revert msal to 0.2.1-SNAPSHOT

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Data storage read API for offline.
`Storage.read` API will read file from cosmos db and cache the file in local storage. In the event of no network ("offline"), `Storage.read` API will read from cache.
~Still missing some unit test coverage for `LocalDocumentStorage.read` API.~

Data storage offline read API

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/Document.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/UtilsTest.java

Storage android sdk’s `Document` class has a method `getError()` that returns a `DocumentError` object which itself has a method `getError()` for the inner storage exception. In order to get the inner exception, you will have to do `doc.getError().getError()`. 
This PR renames `getError()` to `getDocumentError()`.

Rename Document.getError() to .getDocumentError()

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AbstractTokenContextListener.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenInfo.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/CustomPropertiesTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/context/AuthTokenContextTest.java

We need to silently refresh the identity token in the background, so users don’t have to sign in as often.
[AB#57848](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=57848)
[AB#58506](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=58506)

Add automatic token refresh when tokens expire or about to expire.

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java

Move all disk read/writes to background threads to avoid strict mode errors.
Every other module already does that.

Move all disk read/writes to background thread

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/AbstractIdentityTest.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java

Work around for null ID token returned from MSAL.
Since they mark it as `@Nullable` we have to use the `@NonNull` access token as a fallback.
[AB#59718](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=59718)

Use access token if ID token is null

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/ReadOptions.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java

Fix the writeOptions bug, that did not honor the infinite options, and do not update when nocache

Fix incorrect writeOptions apply

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AuthTokenTests.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

Delete the local cache for document storage when a user logs out, and then recreate a new, empty database.
[AB#59537](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=59537)

Purge token cache on user logout

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClient.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientRetryer.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/HttpClientRetryerTest.java

DefaultHttpClient has a constant `RETRY_AFTER_MS_KEY` for `"x-ms-retry-after-ms"` http header. The naming is confusing as `KEY` suffix seems to be referring to key-value pair data structure which stores the headers, which shouldn't be part of the constant name.

Rename constant RETRY_AFTER_MS_KEY to X_MS_RETRY_AFTER_MS_HEADER

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/BaseOptions.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/NetworkStateChangeStorageTest.java

Change default device time-to-live from 1 hour to 1 day.
(https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/60094)

Change default device time-to-live from 1 hour to 1 day

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java

Delete document from cache after successful sync of delete operation
[AB#60223](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=60223)

Delete document from cache after successful sync of delete operation

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/UtilsTest.java

Fix JSON parsing to use UTC ISO dates in storage module

Fix JSON parsing to use UTC ISO dates in storage module

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Following scenario test fails:
1. Create a document with document id that contains spaces (e.g. "Test Document").
2. Retrieve all documents (Storage.list) - make sure the new document is present and its id is "Test Document"
3. Call Storage.read with that document id results in 400 error.
The issue is that we construct DocumentDB Uri without escaping strings that can contain unencoded URI values (e.g. spaces or slashes). 

Adding uriEncoding for CosmosDB calls.

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java

Fix a bug where database cursor is not closed.
```
StrictMode policy violation: android.os.strictmode.SqliteObjectLeakedViolation: Finalizing a Cursor that has not been deactivated or closed. database = /data/user/0/com.microsoft.appcenter.sasquatch.project/databases/com.microsoft.appcenter.documents, table = user_228374e1b08a4c72b2227ce097f0e5c7_documents, query = SELECT * FROM user_228374e1b08a4c72b2227ce097f0e5c7_documents WHERE (partition = ? AND document_id = ?) ORDER BY expiration_time DESC
at android.os.StrictMode.onSqliteObjectLeaked(StrictMode.java:1956)
at …
```

Fix a bug where database cursor is not closed

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java

Sasquatch calls `[MSDataStore setTokenExchangeUrl:kMSIntTokenExchangeUrl];` with INT token exchange URL today, hence the incorrect "https://api.appcenter.ms/v0.1" URL is not used.
Let's fix the default token exchange. We can remove the `setTokenExchangeUrl:` call once token exchange is ready in Prod.
Same change as https://github.com/Microsoft/AppCenter-SDK-Apple/pull/1531.

Fix the default Prod token exchange URL

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/DataActivity.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/DocumentWrapper.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/UtilsTest.java

Fix getJsonValue to return only the customer object and not wrapper.
Fix delete document in sasquatch.
[AB#60477](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/60477)

Fix getJsonValue to return only the customer object and not wrapper / Fix delete document in sasquatch.

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/LocalDocumentStorageTest.java

Fix for [Android] NO_CACHE is not respected for read operation.

---

sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java
sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java

The first sign in always fails for a fresh Android app because the config is not downloaded in time and the app thinks that configuration failed.
Steps to reproduce:
1)Create a new Android app and integrate auth
2)Sign in (you will need to close the app and reopen to get sign in to actually happen)
Expected behavior:
1)Auth sign in method waits asynchronously for the HTTP response to get the remote config if the network is up and if there is no cached config.
2)If the HTTP call fails the completion handler of the sign in API is called with SignInResult with an exception.
3)Sign in immediately fails if …

Sign in always fails on first launch fixed

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

Make the postAsyncGetter() call return a proper document error instead of a null

Make the postAsyncGetter() call return a proper document error instead of a null

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/Constants.java

Add an instance of GroupState for critical events in Analytics (using addGroup), in the same way as it's done in OneCollector. Name it serviceName + "Critical" (this should be Analytics/Critical).
Implement adding events to a different group depending on the priority.
[AB#61308](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61308)

Add a separate Group State for critical events

---

CHANGELOG.md
sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java
sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java

```
E/AppCenter: Timeout waiting for looper tasks to complete.
E/AndroidRuntime: FATAL EXCEPTION: AppCenter.Looper
Process: com.microsoft.appcenter.sasquatch.project, PID: 22199
java.lang.NullPointerException: Attempt to invoke virtual method 'com.microsoft.identity.client.IAccount com.microsoft.identity.client.PublicClientApplication.getAccount(java.lang.String, java.lang.String)' on a null object reference
at com.microsoft.appcenter.auth.Auth.retrieveAccount(Auth.java:543)
at com.microsoft.appcenter.auth.Auth.refreshToken(Auth.java:656)
at com.microsoft.appcenter.auth.Auth.access$100(Auth.java:76)
at com.microsoft.appcenter.auth.Auth$2.run(Auth.java:292)
at com.microsoft.appcenter.AbstractAppCenterService$4.run(AbstractAppCenterService.java:304)
at …
```

Fix NPE in Auth

---

CHANGELOG.md
sdk/appcenter-distribute/src/androidTest/java/com/microsoft/appcenter/distribute/BrowserUtilsTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/BrowserUtils.java

Fix crash when trying to open browser with explicit intent.
Fall back on implicit intent, see #1162 for discussion.
[AB#61928](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61928)

Fix crash when trying to open browser with explicit intent

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/crypto/CryptoUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/crypto/CryptoTest.java

Handle decryption of data that used the expired rotated key.
[AB#61595](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61595)

Handle decryption of data that used the expired rotated key

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/AbstractDefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelPauseResumeTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

Tracking an event with 1min interval / pause / resume after 30s / event is sent after 30s. Pausing doesn’t reset the timer. It’s probably fine since it's the same behavior if paused for any reasons like going to background on iOS or network down.
The issue is the behavior is different if the `trackEvent` happens while pausing; in this case the timer will wait for the entire latency. For instance: Pause / Tracking an event with 1min interval / resume after 30s / event is sent after 1min 30s.
[AB#62192](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/62192)

Fix store interval when channel paused

---

sdk/appcenter-data/src/androidTest/java/com/microsoft/appcenter/data/LocalDocumentStorageAndroidTest.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Utils.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/LocalDocumentStorageTest.java

Bugfix so that on offline update and delete, any previous cached etag value will not be overwritten.
[AB#61109](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61109)

Fix etag being overwritten in cache

---

CHANGELOG.md
sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java
sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java

If you call sign-in before Auth service is started, next time it will fail.
[AB#62968](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/62968)

 Fix signin before start auth never ends and blocks every next try

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/LocalDocumentStorageTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/SQLiteUtils.java

We need to drop both user and readonly tables because we discovered we had been doing inserts instead of upserts into the cache in the original SDK release. Dropping the table will allow to clean up what essentially are duplicate rows (the same partition and document ID, but different `oid`).

Upgrade android Data DB schema version

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Utils.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/DocumentWrapper.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/UtilsTest.java

By default, fields with a null value are excluded from serialization. This change serializes those fields as `null`.
[AB#63856](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/63856)

Serialize null values in DocumentWrapper.

---

CHANGELOG.md
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java

[AB#63924](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/63924)

Fix error report and cache being cleared on disabling Crashes

---

CHANGELOG.md
sdk/appcenter-data/build.gradle

When used without Auth and if the app does not have gson, it would not
pull gson in the app binary before the change.
Fix gradle dependencies for Data module

Fix gradle dependencies for Data module

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClientCallTask.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/DefaultHttpClientTest.java

Redirect URIs were being shown when making calls to auth tenants.  These contain the App Secret, which is not a security credential, but we hide in other logs containing it.  The redirect URI is now completely hidden in logs
[AB#65967](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/65967)

Hide redirect uri in logs

---

CHANGELOG.md
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/PushTest.java

Noticed this while testing something on React Native. Firebase now initialize on its own and can trigger the token update before AppCenter is initialized (which is especially visible with delayed push scenario). And we have an optimization not to send the same token twice but it was used before checking for started/enabled...

Fix delayed start push

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java

Use INT version of the app (projectDependency)
Start with skip start.
Send an event to transmission target 2.
Expected: using one collector.
Actual: Using app center url.
This PR fixes the behavior to be the expected one.

Fix log url for skip start scenario

---

apps/sasquatch/proguard-rules.pro

Found by test team.
Click override common schema on a proguard enabled app build: crash.

Fix proguard in sasquatch for property reflection

---

apps/sasquatch/proguard-rules.pro
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventPropertiesActivity.java

App was crashing when configuring event shared properties in test app UI if proguard was enabled.

Fix proguard config for event shared properties

---

CHANGELOG.md

Reverts microsoft/appcenter-sdk-android#1238
Contrary to Apple, this has always been there in Data module in Android.

Revert "setRemoteOperationListener is not documented"

---

sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java
sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/AuthTokenTests.java
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/PushTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AbstractTokenContextUpdateListener.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterAuthTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/context/AuthTokenContextTest.java

Implement validation for having only 1 token refresh listener.
[AB#67952](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/67952)

Implement validation for having only 1 token refresh listener

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java

The separation between MSA 1DS and Auth was missing in the list.

Add Auth separator in the provider list

---

sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java
sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java

Get authority url from config. This will make sure we can use it later and do not run into null exceptions.
https://github.com/microsoft/appcenter-sdk-android/pull/1241
Yet to make changes to tests

get authority url during init from config

---

apps/sasquatch/google-services.json

Make it crash at Firebase signIn (instead of being stuck in login UI).
Make it crash at Firebase signIn (instead of being stuck in login UI).

Avoid crashing at start if not using the full google-services.json

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterAuthTest.java

As usual, any API that accesses storage cannot be called before AppCenter.start (since that's the one getting the Context).
[AB#69443](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/69443)

Fix crash when trying to set auth token before start

---

CHANGELOG.md
sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java
sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Constants.java
sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java
versions.gradle

This pull request brings android changes for Azure Active Directory (AAD) Authentication. Users can now be authenticated using AAD for their AAD Auth configured app.

Add AAD Auth Feature for Android

---

sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/context/AuthTokenContextTest.java

Fixes an issue where a single token can be refreshed multiple times.
Sorry about the messy history- accidentally pushed to feature branch at first, then reverted, and this pr reverts that revert.
[AB#69442](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/69442)

Fix issue where auth tokens were refreshed multiple times

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/http/HttpConnectionDownloadFileTask.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClientCallTask.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpUtils.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/TLS1_2SocketFactory.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/DefaultHttpClientTest.java

Android 4 release download task doesn't enforce HTTPS during redirects
[AB#69978](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/69978)

Android 4 release download task doesn't enforce HTTPS during redirects

---

CHANGELOG.md
apps/sasquatch/src/androidTest/java/com/microsoft/appcenter/sasquatch/activities/CrashesTest.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchCrashesListener.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManagerAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManager.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/model/ErrorReport.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManagerTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/FileManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/FileManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/FileManagerTest.java

On Java we serialize the exception that caused the crash for client side inspection. Serialization was used to preserve custom fields of the original exception to be available after the app restart.
The problem is that ObjectInputStream.readObject suffers from similar vulnerability as BinaryFormatter on .NET.
This PR removes the insecure implementation of `ErrorReport.getThrowable` and `ErrorReport.setThrowable` (now marked as deprecated and always returns `null`). Provide `ErrorReport.getStackTrace` and `ErrorReport.setStackTrace` as an alternative. …

Android insecure deserialization

---

sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManagerAndroidTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/DefaultHttpClientTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/AppCenterIngestionTest.java

Fix flaky test

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/ManagedErrorActivity.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/HandledErrorTest.java

When we did trackException work for Xamarin, PMs wanted to name it trackError.
To this day this is the name of the concept: "Error" in the Portal.
Java work has always been hidden before.

We never released trackException in Java, it's trackError in .NET

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
versions.gradle

The way we cancel previous downloads since version 2.4.0 is by using the release cache.
If the download was completed successfully, we were not loading the release cache after installing the update (from version A to B), that step was skipped because before version 2.4.0 there was no reason to load release details in that case and the code was not updated.
Thus when receiving the update from B to C, release cache was not pruned because not loaded so the comparison/cancel was skipped in `updateReleaseDetails()`.
#1301 
[AB#71993](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb4 …

Fix in-app update cache issue

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java

Restore logic that clears release details in the "completeWorflow" method. This fixes a bug that would cause a download fail loop after a single failed download for an in app update.

Clear release details on complete workflow

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchCrashesListener.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/ingestion/models/ErrorAttachmentLog.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

Fix validating attachment size to avoid server error
* 4xx error disables channel and cause all logs to be deleted.
* It can also cause out of memory crashes if we don't limit.
[AB#70760](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/70760)

Fix validating attachment size to avoid server error

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java

Keep distribute state on SSL error as it could just be invalid WIFI.
Also remove postpone time if removing token like on iOS.
[AB#73030](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/73030)

Keep distribute state on SSL error as it could just be invalid WIFI

---

CHANGELOG.md
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/FileManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/FileManagerTest.java

- When crashes start, create a random sub-folder
- In that folder, save device properties
- Configure breakpad to save in that folder (modify getMinidumpDir to return sub folder)
- When restarting, process files from each sub folder, minidump gets paired with device properties that are in same folder. Clean up sub-folders on processing.
[AB#70052](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/70052)
[Github issue](https://github.com/microsoft/appcenter-sdk-android/issues/1265/)

Fix Breakpad Crash uploaded as incorrect version when sent after updating the app

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/AppCenterAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/NetworkStateHelper.java

Fixes restart SDK case for instrumentational testing or Xamarin.
Without that we would get:
```
java.lang.IllegalArgumentException: Receiver not registered: 
com.microsoft.appcenter.utils.NetworkStateHelper$ConnectivityReceiver@a502c740
```
or
```
java.lang.IllegalArgumentException: NetworkCallback was already unregistered
```
[AB#74715](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/74715)

Add unset network helper instance method

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/crypto/CryptoUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/crypto/CryptoTest.java

Fix infinite retries on encryption errors that are not related to expiry.
#1348 
[AB#75083](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/75083)

Fix infinite retries on encryption errors that are not related to expiry

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/IdHelper.java

Android SDK can deadlock with distribute while opening browser if the SDK background thread is initializing. The cause is code using `AppCenter.getInstallId.get()` inside `DistributeUtils` to open browser instead of using asynchronous version (`thenAccept`).
#1345
[AB#74885](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/74885)

Fix possible deadlock when activity resumed during SDK background init

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/array.xml
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml

Add UI to switch between Public and Private update track.
[AB#75360](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/75360)

Add UI to switch between Public and Private update track

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java

iOS already has this behavior.
[AB#77140](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/77140)

Allows updates to work on public track if sideloading failed on private

---

CHANGELOG.md
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

This PR removes warning about attachments count when sending crash.
With that, test which was created to verify this message rendered redundant, and so did constant and local counter.
[AB#78240](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/78240)

Remove warning about attachments amount when sending crash report

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java

1. Open application
2. The update dialog is shown. Click downloading.
3. During downloading disable distribute a module. The downloading is stopped.
4. Enable distribute a module. The update dialog is not shown.
5. Collapse and expand the app.
6. The update dialog still is not shown.
Expected
After 4 steps the updates dialog is shown.
Actual
After 4 steps the updates dialog is not shown.

The update dialog is not shown after interrupting downloading

---

CHANGELOG.md
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/FileManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/FileManagerTest.java

Change filter of minidump files fro NDK crash dumps, in the way that only "*.dmp" files can pass. Also clear directory with minidumps files after processing those files. 
Modify time while testing crash to be in seconds instead of milliseconds, because setLastModified do not work correctly with milliseconds, and also when the equal check fails between two dates differs only in milliseconds, it is hard to find a reason, because Date not show milliseconds in string
[AB#78588](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/78588)

Fix filter of minidump files for NDK crash dumps

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/ApplicationLifecycleListener.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/ApplicationLifecycleListenerTest.java

[AB#79328](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/79328)

Fix LifecycleListener when SDK started after onCreate

---

CHANGELOG.md
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/channel/SessionTracker.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AbstractAppCenterService.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelRaceConditionTest.java

During the testing I found that the line with `sendLogs` call can take up to 300-400ms (!), that unacceptable for UI thread. So, I've marked this issue as a bug.
This happens because of call synchronized method (`sendLogs` and status check).
#374, #1421
[AB#81136](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/81136)

Remove sync from UI thread

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/DeviceInfoHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/DeviceInfoHelperTest.java
versions.gradle

Fix deprecated methods usage, update compile and target sdk versions, update tests.
Fix an `IncorrectContextUseViolation` warning when accessing a WindowManager from an Application context on Android 11 in StrictMode.
https://github.com/microsoft/appcenter-sdk-android/issues/1427/
[AB#81390](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/IvanM-Team/Backlog%20Items/?workitem=81390)

Fix IncorrectContextUsage warning

---

scripts/set-ndk-version.sh

~* [ ] Has `CHANGELOG.md` been updated?~
~* [ ] Are tests passing locally?~
~* [ ] Did you add unit tests?~
~* [ ] Did you check UI tests on the sample app? They are not executed on CI.~
Due to [this gradle update](https://developer.android.com/studio/releases/gradle-plugin#default-ndk-version), in case several NDK versions are installed (like [on our CI](https://docs.microsoft.com/en-us/appcenter/build/macos-10.14-software#android-ndks)), it takes the default, not the latest one, so as a result CI uses 18th NDK which breaks the build.
The solution per the documentation is to set the version in gradle: `ndkVersion = '21.3.6528147'`, which we are doing on CI in order not to break local and future builds.
[AB#82284](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472 …

Add a script that uses latest CI NDK version

---

CHANGELOG.md
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/ingestion/models/ErrorAttachmentLog.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/ingestion/models/ErrorAttachmentLogTest.java

Repo steps:
Call this method after AppCenter start.
`ErrorAttachmentLog.attachmentWithText(null, "text.txt");`
[AB#82668](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/82668)

Fix send attachments with null parameter

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/AndroidManifest.xml

Browser doesn't open for private distribution groups on Android 11.
[AB#83712](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/83712)

Browser doesn't open for private distribution groups

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchDistributeListener.java
apps/sasquatch/src/main/res/values/strings.xml
sdk/appcenter-distribute-play/src/main/java/com/microsoft/appcenter/distribute/DistributeListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ErrorDetails.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java

This PR adds a new callback `onNoReleaseAvailable` to DistributeListener.
https://github.com/microsoft/appcenter-sdk-android/issues/1215
[AB#84053](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Ivan-Team/Backlog%20Items/?workitem=84053)
Note: assemble docs task is failing on CI because it uses jcenter dependency, not project one.

Add onNoReleaseAvailable callback

---

CHANGELOG.md
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManagerAndroidTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/UncaughtExceptionHandlerTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManagerTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java

Repro steps:
- Build and run the Sasquatch app in debug mode from Android Studio.
- Set the storage size to 32768 (32kb).
- Turn off Wi-Fi and LTE, so there's no network on the device/emulator.
- Crash the app several times (7-10 times).
- Turn on Wi-Fi/LTE.
- Run the Sasquatch app in debug mode from Android Studio, open Device File Explorer in the IDE and see extra throwable files.
**Actual:**
There are several .throwable files that are not cleaned up even after restart.
**Expected:**
After network turned on .throwable files should be cleaned up. …

Remove throwable files

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchDistributeListener.java
apps/sasquatch/src/main/res/values/strings.xml
sdk/appcenter-distribute-play/src/main/java/com/microsoft/appcenter/distribute/DistributeListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ErrorDetails.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java

This PR adds a new callback `onNoReleaseAvailable` to DistributeListener.
https://github.com/microsoft/appcenter-sdk-android/issues/1215
[AB#84053](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Ivan-Team/Backlog%20Items/?workitem=84053)
Note: assemble docs task is failing on CI because it uses jcenter dependency, not project one.

Add onNoReleaseAvailable callback feature

---

sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeWarnUnknownSourcesTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AbstractAppCenterService.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/DeviceInfoHelperTest.java
sdk/build.gradle

The code coverage has been broken on Android since we bumped up the Gradle plugin version. 
This PR:
- Fixes the code coverage task
- Adds and changes tests to reach 100% coverage
- Removes unused methods (postOnUiThread & runIfEnabled)
[AB#84105](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Ivan-Team/Backlog%20Items/?workitem=84105)

Fix coverageReport gradle task

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerReleaseDownloader.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTask.java
sdk/appcenter-distribute/src/main/res/values/appcenter_distribute.xml
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTaskTest.java

The title has not clear information on the push notification during downloading new release.
**Expected behavior**
Title should contains information about downloading release (version and short version)
**Actual behavior**
Title contains `<Untitled>` string instead.
[AB#84082](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/84082)

Fix show title in the push notification

---

CHANGELOG.md
sdk/appcenter-distribute/proguard-rules.pro
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTask.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTaskTest.java

Fix crash during downloading a new release with a specific Gradle configuration.
**Repo steps:**
- Create empty app.
- Add these lines to the app gradle:
```
release {
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
}
```
- Run the app and press on download button on the in-app update dialog.
**Expected behavior:**
Release successfully downloaded.
**Actual behavior:**
App crashes.
[AB#86011](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/86011)

Fix crash during downloading a new release

---

apps/sasquatch/src/main/AndroidManifest.xml
sdk/appcenter-distribute/src/main/AndroidManifest.xml

Android 12 requires to declare the`android:exported` attribute explicitly for components with `intent-filter`
Documentation link: https://developer.android.com/about/versions/12/behavior-changes-12#exported
Issue: https://github.com/microsoft/appcenter-sdk-android/issues/1506

Issue #1506. Declared android:exported explicitly for components with intent-filter. Android 12 requirement

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDownloadListener.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerDistributeDeadlockTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/TimeoutExpected.java

This PR fixes the rare deadlock case when a new version starts downloading and at the same moment the download status is checked (along with a few other cases). The approach is the following: ease up the locking on one side of communication between the downloader and the main module by posting calls to the main module on the UI thread.
https://github.com/microsoft/appcenter-sdk-android/issues/1533
[AB#86784](https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Mobile%20SDK/Backlog%20Items/?workitem=86784)
Deadlock stacktraces: …

Fix Distribute module ANR issue

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java

Fix intent flag for android apps lower 23 API.
[AB#87052](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/87052)

Fix intent flag for android apps lower 23 API

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/StartServiceLog.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/StartServiceLogTest.java

Add a new property to startService log.
[AB#89379](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89379)

Add a new property isOneCollectorEnabled to startService log

---

CHANGELOG.md
apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/ActivityConstants.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
versions.gradle

1) Add null check before showing settings dialog
2) Fix UI for transmission interval
3) Fix crash. Repro steps:
- Launch app - see in-app update dialog
- Disable network connection and press on download button
- Close application
- Start the application again and enable network connection.
- Wait when downloading new release was completed and see confirmation dialog about installing a new release
- Discard installing the new release
- See crash:
```
Crashes.getLastSessionCrashReport().getStackTrace()=java.lang.NullPointerException: Attempt to invoke virtual method 'boolean …
```

Patch with fixes after testing release 4.4.0

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppStoreDetectionTest.java

**Repro steps:**
1. Build the current app (v1.0) and distribute it from within the App Center
2. Download the app from the App Center (v1.0), then install it
3. Build and distribute another update (v1.1)
4. Open the app (v1.0), it would detect the update, then install it, this process will work fine
5. Build and distribute another update (v1.2)
6. Open the app(v1.1), the app won't detect the update, at this point any other updates won't be detected by the app. However, if I uninstall the currently installed app, then redownload the app (v1.1) from within the App Center, the app would detect the update …

Fix checking a new release

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/AppCenterPackageInstallerReceiver.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppCenterPackageInstallerReceiverTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeWarnAlertSystemWindowsTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeWarnUnknownSourcesTest.java

[AB#91443](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/91443)
#1603

Fix superfluous register/unregister receiver for installing new release

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeConstants.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeUtils.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDownloadListener.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeUtilsTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/ReleaseDownloadListenerTest.java

App doesn't resume when the user clicks on the download notification.
#1613
[AB#91962](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/91962)

Fix clicks on the download notification

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ApplicationContextUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterLibraryTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ApplicationContextUtilsTest.java

* ~[ ] Did you check UI tests on the sample app? They are not executed on CI.~
Added protected storage for data in direct boot mode.
#1599
[AB#91315](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/91315)

Fix crash when direct boot

---

apps/sasquatch/build.gradle

Currently the Sasquatch App version is coupled with the AppCenter Android SDK version due to the unity of the versioning in the versions.gradle file.
This coupling will raise an issue when trying to test the distribute feature with the latest SDK module, here's an example scenario:
I want to verify that the distribute feature works as expected for the new app center sdk version (5.0.0)
If I downgrade the version from the versions.gradle file (let's say to 4.0.0) for the sake of downgrading the Sasquatch application to test the distribute behaviour, the sdk's version is thus downgraded as well (which …

Decouple versioning of sasquatch app from SDK

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java

My initial thoughts around this issue:
The issue is happening under the scenario of which the distribute SDK needs to show the "Update Setup Failed" dialog. 
When the "showUpdateSetupFailedDialog" method is called, the alert dialog uses the global variable activity instance mForegroundActivity.
The mForegroundActivity in the above scenario is null. Thus the crash.
How could this variable be null? Let's observe the workflow:
In our Distribute.java class, mForegroundActivity is a global private variable used in the scope of this class.
The value of the mForegroundActivity is set under the following two …

Fix NPE in Distribute module on resume workflow

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/NetworkStateHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/NetworkStateHelperTestFromLollipop.java

* ~[ ] Did you check UI tests on the sample app? They are not executed on CI.~
Add try/catch for capture NullPointerException in NetworkStateHelper.isAnyNetworkConnected
https://github.com/microsoft/appcenter-sdk-android/issues/1679
[AB#100301](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/100301)

Add catching RuntimeException

---

CHANGELOG.md
sdk/appcenter-distribute/src/androidTest/java/com/microsoft/appcenter/distribute/ReleaseDetailsTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeConstants.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/FileExtension.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDetails.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerReleaseDownloader.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerReleaseDownloaderTest.java

Added the `is_install_page=true` parameter to the URL for the release details request in order to receive a link to download the APK file even if an ABB file has been uploaded to the portal. Also, due to the fact that when uploading an AAB file to the portal, the release details indicate the size of the AAB file, even if we download the APK file, we ignore the check of the size of the uploaded file in this case.

Ignore file size check if original update file has AAB extension format

---

CHANGELOG.md
apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/install/session/SessionReleaseInstaller.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/AbstractLog.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/Log.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/ChannelLogDecorateTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/AbstractLogTest.java
versions.gradle

- Add dataResidencyRegion option for sending to portal #1704

Version 5.0.3

---

README.md

Documentation-only change.
Bintray has been discontinued - removing the broken header link.
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/microsoftappcentersdkandroid/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project. In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.
none

docs: remove dead link and add link to repository map in README.md

---

CHANGELOG.md
README.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/install/session/InstallStatusReceiver.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/install/session/SessionReleaseInstaller.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/install/session/InstallStatusReceiverTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/install/session/SessionReleaseInstallerTest.java
versions.gradle

- Add FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT flag for broadcast pending intent and RECEIVER_EXPORTED flag for install receiver. https://github.com/microsoft/appcenter-sdk-android/pull/1713

Version 5.0.4

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientRetryer.java

The "Insufficiently Random Values" alert references the `HttpClientRetryer` file, which uses random values in a non-security context, specifically for creating timeouts for retries. But to avoid this warning, we migrate to `java.security.Random` package.
Issue: [#1032](https://github.com/microsoft/appcenter-sdk-react-native/issues/1032/)
[AB#107228](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/107228)
[Build succeed
](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1535175&view=results)

Migrate to java.security.Random instead

---

.azurepipelines/azure-maven-template.yml
.azurepipelines/publish-maven-1ES.yml

This PR introduces a new stage in the CI pipeline for publishing artifacts to Azure Maven Artifacts. The artifacts are published with the commit hash included in their version to avoid conflicts during the release process.
Additionally, removed ESRP publish task, as it should be done in the release pipeline.
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1541557&view=results)
[AB#107584](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/107584)

[CI] Add publishing to Azure Maven Artifacts

---

scripts/run-code-coverage.sh

During pipeline execution, the emulator encountered errors while attempting to install APKs during testing. This issue was likely caused by running the `gradlew coveralls` command with the `--parallel` flag, which led to multiple APK installations occurring simultaneously. To resolve this, we have removed the `--parallel` flag from the command.
[AB#107754](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/107754)

Fix Build and Test pipeline

---

scripts/run-code-coverage.sh

Added additional arguments to the emulator boot process to reduce the occurrence of installation exceptions on CI `com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unknown failure: cmd: Can't find service: package`
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1551477&view=results)
[#AB107754
](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/Mobile%20SDK%20team/Backlog%20Items?System.AssignedTo=v-djordjed%40microsoft.com&workitem=107754)

Add arguments to Emulator boot process

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeWarnUnknownSourcesTest.java

Dismiss dialog window instead of hiding it. We usually don't use this dialog more than once per application launch, so there's no point in saving resources on creating this dialog. This allows us to correctly remove the dialog from any thread.
[Build succeeded](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1551727&view=results)
https://github.com/microsoft/appcenter/issues/2647
https://github.com/microsoft/appcenter-sdk-android/issues/1747
[AB#109350](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/109350)

Dismiss dialog instead of hiding it

---

.azurepipelines/build-demo-app.yml

Because of CodeQL analysis recognizes this repository as containing C++ code, we need to build C++ files during the CodeQL scan (even if not all of them). Currently, the repository has only one C++ file—in Sasquatch app and this file is part of the functionality (testing the handling of crashes that were raised from native C++ code) of this application.
This pull request introduces a pipeline configuration that builds Sasquatch app as part of the CodeQL scan. This ensures that CodeQL successfully scan C++ code in its analysis.
[Build succeeded](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1546315&view=results)
[AB#107387](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/107387)

Sasquatch app build with CodeQL analysis

---

.azurepipelines/azure-maven-template.yml

Fix stage name in dependsOn option for PublishAzureMaven
[Build succeed](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1552655&view=results)
[AB#109330](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/109330)

Fix dependsOn for azure-maven-template.yml
