microsoft/appcenter-sdk-android

README.md

This is a Bintray official badge so it shouldn't have the problem.

Add back bintray badge

---

apps/sasquatch/build.gradle
versions.gradle

To merge fist before other prs

Start new version

---

README.md

Port of https://github.com/Microsoft/mobile-center-sdk-xamarin/pull/68

Improve wording for crash user confirmation

---

sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/ingestion/http/IngestionNetworkStateHandler.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/utils/UUIDUtils.java

Jacoco does not like synchronized (object)

Refactor synchronization logic to fix local coverage report

---

sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/Crashes.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/CancellationException.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/channel/Channel.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/channel/DefaultChannel.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/persistence/DatabasePersistenceAsync.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/channel/DefaultChannelTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/persistence/DatabasePersistenceAsyncTest.java

Posting the PR early before tests so that we can discuss the design.

Wait logs to be flushed on disk on crash

---

versions.gradle

Lint complains about it. Updating support lib version to 25.1.0.

Update support library version

---

README.md

By changing color, it defeats the invalid cache of github...

Fix licence badge

---

sdk/mobile-center-updates/src/main/java/com/microsoft/azure/mobile/updates/InstallerUtils.java
sdk/mobile-center-updates/src/main/java/com/microsoft/azure/mobile/updates/Updates.java
sdk/mobile-center-updates/src/main/res/values/strings.xml
sdk/mobile-center-updates/src/test/java/com/microsoft/azure/mobile/updates/AbstractUpdatesTest.java
sdk/mobile-center-updates/src/test/java/com/microsoft/azure/mobile/updates/AppStoreDetectionTest.java
sdk/mobile-center-updates/src/test/java/com/microsoft/azure/mobile/updates/UnknownSourcesDetectionTest.java
sdk/mobile-center-updates/src/test/java/com/microsoft/azure/mobile/updates/UpdatesBeforeDownloadTest.java
sdk/mobile-center-updates/src/test/java/com/microsoft/azure/mobile/updates/UpdatesDownloadTest.java
sdk/mobile-center-updates/src/test/java/com/microsoft/azure/mobile/updates/UpdatesWarnUnknownSourcesTest.java

* Fix flickering on dialogs.
* Show toast when dialog click canceled by disabling module.

Show dialog when unknown sources are disabled

---

sdk/mobile-center-updates/src/main/java/com/microsoft/azure/mobile/updates/Updates.java
sdk/mobile-center-updates/src/test/java/com/microsoft/azure/mobile/updates/UpdatesBeforeApiSuccessTest.java

I target my previous pr as it will conflict otherwise... Please review #329 first.

Keep token when disabling updates

---

README.md

Changed documentation to include Distribute service APIs.

Updated documentation for Distribute service

---

sdk/mobile-center-push/src/main/java/com/microsoft/azure/mobile/push/Push.java

Push service now sends token in real time similar to Crashes service

Push service changed to send token in real time

---

sdk/mobile-center-analytics/src/main/java/com/microsoft/azure/mobile/analytics/Analytics.java
sdk/mobile-center-crashes/src/main/java/com/microsoft/azure/mobile/crashes/Crashes.java
sdk/mobile-center/src/androidTest/java/com/microsoft/azure/mobile/ingestion/models/json/JSONUtilsAndroidTest.java
sdk/mobile-center/src/androidTest/java/com/microsoft/azure/mobile/ingestion/models/json/LogSerializerAndroidTest.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/AbstractMobileCenterService.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/Constants.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/MobileCenter.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/MobileCenterService.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/ingestion/models/StartServiceLog.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/ingestion/models/json/JSONUtils.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/ingestion/models/json/StartServiceLogFactory.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/AbstractMobileCenterServiceTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/MobileCenterTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/channel/DefaultChannelTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/ingestion/models/StartServiceLogTest.java
versions.gradle

Added start service log with list of used services. Also added tests for it.

Added telemetry

---

apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/env.xml
apps/sasquatch/src/projectDependency/res/values/env.xml
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/DistributeConstants.java
versions.gradle

Also remove reflection for distribute in test app.

Use pre-release in test app, fix API URL

---

sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/Distribute.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/DistributeConstants.java
sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/DistributeUtils.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/AbstractDistributeTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeBeforeApiSuccessTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeBeforeDownloadTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeDownloadTest.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeHttpTest.java

Refactor to get package info once to simplify exception handing

Add release_hash to query string when checking releases

---

apps/sasquatch/src/main/AndroidManifest.xml
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/CustomPropertiesActivity.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/LogActivity.java
apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/features/TestFeatures.java
apps/sasquatch/src/main/res/drawable/border.xml
apps/sasquatch/src/main/res/layout/activity_custom_properties.xml
apps/sasquatch/src/main/res/layout/custom_property.xml
apps/sasquatch/src/main/res/layout/property.xml
apps/sasquatch/src/main/res/menu/add.xml
apps/sasquatch/src/main/res/values/strings.xml
sdk/mobile-center/src/androidTest/java/com/microsoft/azure/mobile/ingestion/models/json/LogSerializerAndroidTest.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/CustomProperties.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/MobileCenter.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/ingestion/models/CustomPropertiesLog.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/ingestion/models/json/CustomPropertiesLogFactory.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/CustomPropertiesTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/MobileCenterTest.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/ingestion/models/CustomPropertiesLogTest.java

Implemented custom properties feature by spec

Custom properties feature

---

sdk/mobile-center-analytics/src/main/java/com/microsoft/azure/mobile/analytics/Analytics.java
sdk/mobile-center-analytics/src/test/java/com/microsoft/azure/mobile/analytics/AnalyticsTest.java

Properties validation implemented in Analytics track methods

Validation of track methods properties

---

README.md

This is our new, awesome readme.

Add new, shortened readme

---

sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/MobileCenter.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/MobileCenterTest.java

Also change error log to be closer to iOS one.

Fix crash when calling MobileCenter.setCustomProperties before start

---

sdk/mobile-center-distribute/src/main/java/com/microsoft/azure/mobile/distribute/Distribute.java
sdk/mobile-center-distribute/src/test/java/com/microsoft/azure/mobile/distribute/DistributeBeforeApiSuccessTest.java
sdk/mobile-center-push/src/main/java/com/microsoft/azure/mobile/push/Push.java
sdk/mobile-center-push/src/test/java/com/microsoft/azure/mobile/push/PushTest.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/AbstractMobileCenterService.java
sdk/mobile-center/src/main/java/com/microsoft/azure/mobile/MobileCenter.java
sdk/mobile-center/src/test/java/com/microsoft/azure/mobile/MobileCenterTest.java

Missing push for now, will add to this PR if not yet merged by then.

Fix strict mode activity lifecycle

---

apps/sasquatch/src/main/java/com/microsoft/azure/mobile/sasquatch/activities/MainActivity.java

No more reflection needed as available in jCenter too

Use Push.checkLaunchedFromNotification directly

---

localization/TouchDownCheckinScript.ps1

Changing loc script to run in develop

---

localization/LocCleanup.sh
localization/TouchDownCheckinScript.ps1

Git auth is required to push localized files to the correct branch.

Use authenticated git

---

versions.gradle

Bump minor version

---

localization/mobile-center-distribute/cs-CZ/mobile_center_distribute.xml
localization/mobile-center-distribute/de-DE/mobile_center_distribute.xml
localization/mobile-center-distribute/es-ES/mobile_center_distribute.xml
localization/mobile-center-distribute/fr-FR/mobile_center_distribute.xml
localization/mobile-center-distribute/it-IT/mobile_center_distribute.xml
localization/mobile-center-distribute/ja-JP/mobile_center_distribute.xml
localization/mobile-center-distribute/ko-KR/mobile_center_distribute.xml
localization/mobile-center-distribute/pl-PL/mobile_center_distribute.xml
localization/mobile-center-distribute/pt-BR/mobile_center_distribute.xml
localization/mobile-center-distribute/ru-RU/mobile_center_distribute.xml
localization/mobile-center-distribute/tr-TR/mobile_center_distribute.xml
localization/mobile-center-distribute/zh-CN/mobile_center_distribute.xml
localization/mobile-center-distribute/zh-TW/mobile_center_distribute.xml

Feel free to chime in if any of the translations are incorrect/misleading.

Latest localized files from touchdown

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchCrashesListener.java

Reproduction:
1. Select file attachment
2. Reboot
3. Go to settings or send crash

Catch security exception on read file attachment

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/res/values-cs/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-de/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-es/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-fr/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-it/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-ja/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-ko/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-pl/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-pt/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-ru/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-tr/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-zh-rCN/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values-zh-rTW/appcenter_distribute.xml
sdk/appcenter-distribute/src/main/res/values/appcenter_distribute.xml
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java

The localized strings are not from TouchDown. We need to localize again.

Add text for Distribute UI

---

CONTRIBUTING.md

Hi @guperrot, we are going to work with this repo intensively during this and next months, so we want to provide you contribution guideline that should help us to improve code quality and speed up development. 
So, please review and let us know if you have considerations or see any issues.

Contribution guideline

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterServiceTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

Fix tests for transmission target branch

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/array.xml
apps/sasquatch/src/main/res/values/env.xml
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
apps/sasquatch/src/projectDependency/res/values/env.xml

Do not merge yet!
Waiting for PR #638 to be merged

Setting for choosing appcenter start type added

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
sdk/build.gradle

* verified using both build jobs to create artifacts
* verified by integrating artifacts in simple app (sources available)
* verified by building test app in App Center

Update jacoco, gradle and android gradle plugin versions

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/InstrumentationRegistryHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java

Resolution for problem raised at https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/664.

Fix another crash for checking instrumentation environment

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/OneCollectorChannelListener.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/OneCollectorChannelListenerTest.java

Merge #668 and change target branch before merge

Add one collector log group when sending eligible appcenter logs 

---

sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AbstractAppCenterService.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/Channel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/OneCollectorChannelListener.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterServiceTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/ChannelLogDecorateTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelRaceConditionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/OneCollectorChannelListenerTest.java

Work in Progress for alternate ingestion.

Alternate Ingestion

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/ingestion/models/one/json/CommonSchemaEventLogFactory.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/ingestion/models/one/json/CommonSchemaEventLogFactoryTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/PartCUtilsAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/Data.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartCUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/PartCUtilsTest.java

Event properties go to part C.

Handle Part C in events

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactory.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/ingestion/models/one/json/CommonSchemaEventLogFactory.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactoryTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/ingestion/models/one/json/CommonSchemaEventLogFactoryTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/json/DefaultLogSerializer.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartAUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/PartAUtilsTest.java

Fix event conversion to common schema

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/MockCommonSchemaLog.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/MockCommonSchemaLogFactory.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/PersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/StorageHelperAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/AbstractLog.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/StorageHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/AbstractLogTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/persistence/DatabasePersistenceTest.java

Persist target token

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/AppCenterIngestion.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelRaceConditionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/AppCenterIngestionTest.java

About to introduce OneCollectorIngestion alternate implementation.

Rename IngestionHttp to AppCenterIngestion

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaLogSerializerTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/LocExtension.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartAUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/ExtensionsTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/LocExtensionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/PartAUtilsTest.java

Well, turns out the right key was tz, reverting...

Fix common schema timezone property

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactory.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactoryTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/PartCUtilsAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/OneCollectorChannelListener.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/OneCollectorIngestion.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartAUtils.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartCUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/OneCollectorChannelListenerTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/PartAUtilsTest.java

Merge after #708 and branch retargeted to transmission.

Common Schema input validation

---

versions.gradle

Update version name to 1.6.0

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java

For now it's not useful as no setProperty or isEnabled/setEnabled but will come later and will benefit from nesting.

Nest transmission targets

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java

Adding setEventProperty, removeEventProperty, and tests

Adding setEventProperty, removeEventProperty, and tests

---

sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

Add more checks in the crashes tests

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java

https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/717/

Fix NPE on recreate launch activity before full initialization

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java

Was checked but without logging.

Log error message if target token null or empty

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/MSALoginActivity.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClient.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpUtils.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/OneCollectorIngestion.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/OneCollectorIngestionTest.java

Also fix some deprecation warnings

 Hide tokens in logs

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaLogSerializerTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/DeviceExtension.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/Extensions.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/DeviceExtensionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/ExtensionsTest.java

Device ID will not be inherited by children.

Allow collection of device ID from property configurator

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/DeviceInfoActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
apps/sasquatch/src/main/res/layout/activity_event.xml
apps/sasquatch/src/main/res/values/strings.xml
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/PartAUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/PartAUtilsTest.java

 Add UI for device id to test application

---

CHANGELOG.md

Forgot to do this in the main PR #796

Updating changelog for setStorageSize feature

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
apps/sasquatch/src/main/res/layout/activity_event.xml
apps/sasquatch/src/main/res/values/strings.xml

Adding UI for transmission target pause/resume

---

codecov.yml

We already switched to coveralls.

Delete codecov config

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/DeviceExtension.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/OsExtension.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/UserExtension.java

Some files have unsupported encoding that breaks gradle build. #827

Replace double quotes in CP1252 encoding

---

apps/sasquatch/src/jcenterDependency/java/com/microsoft/appcenter/sasquatch/activities/EventPropertiesActivity.java
apps/sasquatch/src/jcenterDependency/res/layout/activity_event_properties.xml
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/fragments/CustomPropertyFragment.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/fragments/EditDateTimeFragment.java
apps/sasquatch/src/main/res/layout/activity_event_properties.xml
apps/sasquatch/src/main/res/layout/custom_property.xml
apps/sasquatch/src/main/res/values/strings.xml
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/EventPropertiesActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/fragments/TypedPropertyFragment.java
apps/sasquatch/src/projectDependency/res/layout/activity_event_properties.xml
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/PropertyConfigurator.java

Test App UI for common typed properties

---

PULL_REQUEST_TEMPLATE.md

This adds the PR template file that we've added to the Apple SDK repo.

Add a PR template file

---

build.gradle
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/OneCollectorIngestion.java

Optional check must pass for this one.

Update Android gradle plugin and fix a Javadoc warning

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelAlternateIngestionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelPauseResumeTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelRaceConditionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

A pr to fix the new code analysis issues found by Android Studio 3.2.
Ideally merged before refactoring enqueueItem to add priority.

Fix warnings in channel

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterInstrumentationTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/persistence/DatabasePersistenceTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/DatabaseManagerTest.java

Implement persistence flag for purge of the logs.

Purge critical logs last

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/CrashActivity.java
apps/sasquatch/src/main/res/values/crashes.xml
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClient.java

Just catching with develop and merging conflicts early before we forget context.

Merge develop to priority feature branch

---

PULL_REQUEST_TEMPLATE.md
apps/sasquatch/src/androidTest/java/com/microsoft/appcenter/sasquatch/activities/AnalyticsTest.java
apps/sasquatch/src/androidTest/java/com/microsoft/appcenter/sasquatch/activities/CrashesTest.java
apps/sasquatch/src/jcenterDependency/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchAnalyticsListener.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchCrashesListener.java
apps/sasquatch/src/main/res/layout/activity_event.xml
apps/sasquatch/src/main/res/values/strings.xml
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java

Send multiple events at once in UI

---

sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java

Just a merge with conflict resolution.

Merge develop to priority

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/channel/SessionTracker.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/PropertyConfiguratorTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/channel/SessionTrackerTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/PushTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/Flags.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterLibraryTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/FlagsTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/ChannelLogDecorateTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelAlternateIngestionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelOtherOperationsTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelPauseResumeTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/OneCollectorChannelListenerTest.java

Rename default flags

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java

Add flags to trackEvent(String, Map)

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

Create index on priority table

Create index on priority table

---

CHANGELOG.md
versions.gradle

Bump minor version and update changelog.

Bump minor version and update changelog

---

CHANGELOG.md
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

`setMaxStorageSize` returns false if database page size is not 4KiB

setMaxStorageSize returns false if database page size is not 4KiB

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml

Implement UI to test userId on AppCenter

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/CommonSchemaPropertiesActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/projectDependency/res/values/strings.xml

Implement UI to test userId on AnalyticsTransmissionTarget

---

sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/ingestion/models/ErrorModelTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/DefaultHttpClientTest.java

Some piece of code was covered accidentally in unrelated test and not guaranteed.

Add unit test to cover huge payload logging

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MSALoginActivity.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeAfterDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeHttpTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeWarnUnknownSourcesTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/http/HttpUtilsAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClient.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClientCallTask.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientCallDecorator.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientNetworkStateHandler.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpUtils.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/ServiceCall.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/AppCenterIngestion.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/OneCollectorIngestion.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/NetworkStateHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/DefaultHttpClientTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/HttpClientNetworkStateHandlerTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/AppCenterIngestionTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/OneCollectorIngestionTest.java

The SDK doesn't cancel http request correctly when a network connection is lost.

Fix logs duplication

---

sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-push/src/test/java/com/microsoft/appcenter/push/PushTest.java

Add user id in push installation log

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactory.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/ingestion/models/json/EventLogFactoryTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaDataUtilsAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaLogSerializerTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaDataUtils.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/Data.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaDataUtilsTest.java

Part B validation changes

---

CHANGELOG.md

Update changelog for userId in push logs

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaLogSerializerTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/DataTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/Data.java

Serialize part B before part C.

Serialize part B before part C

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaDataUtilsAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/one/CommonSchemaDataUtils.java

* Fix baseType validation against object.
* Add some unit tests that were used in Apple implementation.

Fix baseType validation against object

---

build.gradle

`Could not find com.google.gms:google-services:4.0.1.`

Fix build issue

---

CHANGELOG.md
versions.gradle

Updated the ChangeLOG.md file for december release
Pre-releasing the SDK. Submiting a PR to merge branch 1.10.1 into develop

Updated CHANELOG.md for 1.11.0

---

apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/CommonSchemaPropertiesActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MSALoginActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/strings.xml
apps/sasquatch/src/projectDependency/res/values/strings.xml

TODOs updated to sasquatch
We updated the Build.gradle for sasquatch app and updated the TODO list. 
We tested the functionality of the app in emulator.

Use new SDK in demo app

---

README.md

We don't want to refer to the service we use for support, especially if we ever change the service. Removed the word Intercom and updated the content based on what we already send to people who comment on the docs.

Removed Intercom

---

apps/sasquatch/src/projectDependency/res/values/env.xml

Fix in-app updates for sample app on INT

---

apps/sasquatch/src/projectDependency/res/values/env.xml

Fix in app updates URL for INT (project dependency).

Fix API url for int

---

CHANGELOG.md
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/channel/SessionTracker.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/channel/SessionTrackerTest.java

1. Schedule track event every 30s
2. Minimize the app into the background
3. Observe that every event creates a new session
Expected behavior:  
Like iOS, sending a log just extends current session lifetime but must not trigger a new session.

Don't start session from logs

---

CHANGELOG.md

Updated CHANGELOG.md file

---

sdk/appcenter/proguard-rules.pro
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClientCallTask.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/TLS1_2SocketFactory.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/DefaultHttpClientTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/Tls1_2SocketFactoryTest.java

Fix TLS 1.2 on some Android 4.x devices

---

CHANGELOG.md
versions.gradle

Version bump and changelog for TLS hot fix.

Version bump and changelog for TLS hot fix

---

apps/sasquatch/build.gradle

Changed the version number in  build.gradle file. 

Version change in build.gradle .

---

apps/sasquatch/build.gradle
versions.gradle

Updated version.gradle with next version code and release number. 

Updated version.gradle with next release number

---

CHANGELOG.md
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/persistence/DatabasePersistenceTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/DatabaseManagerTest.java

Handle SQLite errors from get/set max size methods gracefully.

Handle some SQLite errors gracefully

---

CONTRIBUTING.md
apps/sasquatch/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties
scripts/publish-github-release.sh
scripts/publish-storage-account.sh
sdk/appcenter-push/build.gradle
sdk/build.gradle
versions.gradle

Fix compatibility with Android Studio 3.3

Fix compatibility with Android Studio 3.3

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppStoreDetectionTest.java

https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/804

Fix checking updates for applications installed on corporate-owned single-use devices

---

CHANGELOG.md

Updating the changelog file with latest version

Updating the changelog file with latest version

---

apps/sasquatch/build.gradle

Merging the changes from demo app branch to master
* [ X] Has `CHANGELOG.md` been updated?
* [ X] Are tests passing locally?
* [X ] Did you check UI tests on the sample app? They are not executed on CI.

Version changes in build.gridle file

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientNetworkStateHandler.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/NetworkStateHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/NetworkStateHelperTestBeforeLollipop.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/NetworkStateHelperTestFromLollipop.java

Fix network connection state tracking
#941

Fix network connection state tracking

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java
sdk/appcenter-rum/src/main/java/com/microsoft/appcenter/rum/RealUserMeasurements.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java

Javadoc improvement
https://github.com/MicrosoftDocs/appcenter-docs/issues/463/

Add note to the java doc

---

sdk/appcenter-identity/src/androidTest/java/com/microsoft/appcenter/identity/storage/TokenStorageTest.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/storage/AuthTokenStorage.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/storage/PreferenceTokenStorage.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/storage/TokenStorageFactory.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/AbstractIdentityTest.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/storage/TokenStorageTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelCallbacksTest.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/context/AuthTokenContextTest.java

Need to persist the encrypted token. 
#950

Identity persist token

---

build.gradle

Update Android Studio gradle plugin

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java
versions.gradle

Reverted API version to min supported v16

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/StorageActivity.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeConstants.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/Document.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/TokenResult.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/TokensResponse.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

- Refactored Token Exchange and Cosmos DB service calls. 
- Added future management.

Refactored Token Exchange and Cosmos DB service calls. Added future management.

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java

Rename login method to signIn
WorkItem: https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Doug-Team/Backlog%20Items

Rename login to sign in

---

sdk/appcenter-identity/build.gradle

Update SDK dependencies to benefit from a bug fix with facebook login.

Fix facebook login

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/StorageActivity.java
apps/sasquatch/src/main/res/layout/activity_storage.xml
apps/sasquatch/src/main/res/values/strings.xml
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/exception/TokenExchangeException.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/Document.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/TestDocument.java

* [-] Has `CHANGELOG.md` been updated?
* [+] Are tests passing locally?
* [+] Are the files formatted correctly?
* [+] Did you add unit tests?
* [+] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?
* [+] Did you check UI tests on the sample app? They are not executed on CI.
- Added document type parameter to Storage method signatures to work around Java erasure
- Tests coverage is almost 100%, going to add a few more tests with the next commit to this PR

Added document type parameter to Storage method signatures and more tests

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/storage/AuthTokenStorage.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/storage/PreferenceTokenStorage.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AbstractTokenContextListener.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java

Added signOut method 
WorkItem: https://msmobilecenter.visualstudio.com/Mobile-Center/_boards/board/t/Doug-Team/Backlog%20Items

Added signOut method

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/SignInResult.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/UserInformation.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/storage/AuthTokenStorage.java
sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/storage/PreferenceTokenStorage.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/AbstractIdentityTest.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/storage/TokenStorageTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java

Replace void by SignInResult in signIn method.

Sign in result

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java
apps/sasquatch/src/main/res/values/strings.xml

Added sign out button in sasquatch app
#963

Added sign out button

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java

Address https://github.com/Microsoft/AppCenter-SDK-Android/pull/977#issuecomment-469585533

Fix synchronization issue

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/PaginatedDocuments.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/TokenResult.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/TokenTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/UtilsTest.java

Fix the coverage test

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/NetworkStateHelper.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/HttpClientNetworkStateHandlerTest.java

Fixed deadlock in NetworkStateHelper

---

apps/sasquatch/build.gradle

Updated with latest version number

Update SDK version in the demo application

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java

Fix Sign in without internet connection is delayed instead of failing.
[AB#58000](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=58000)

Fix Sign in without internet connection is delayed instead of failing

---

versions.gradle

Updated versionCode and versionName for next SDK release

Start a new version

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java

Update `setUserId` API comment as App Center backend already supports set user ID feature.
See https://github.com/Microsoft/AppCenter-SDK-Apple/pull/1377 for the same fix on Apple SDK.

Update out-of-date setUserId comment

---

sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/DocumentCacheTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

add test case for upsert

---

sdk/appcenter-storage/build.gradle
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/DocumentCache.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/DocumentCacheTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/DatabaseManagerTest.java

Rename upsert by replace and add more tests.
Android Studio does not like upsert word.

Rename SQLite upsert by replace and add more tests

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/DocumentCacheAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/DocumentCache.java

Test cache expiration and remove a useless check.

Test cache expiration and remove a useless check

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/StorageHttpClientDecorator.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientDecorator.java

Implemented a version of `HttpDecorator` that handles offline mode simulation flag and used it at the top of the existing decorator hierarchy.

Add offline mode simulation to Storage

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Update draft documents storage to use new SQLite schema:
- Added extra fields to the schema and renamed non-matching existing ones
- Renamed `DocumentCache` to `LocalDocumentStorage`
Did not change any of the behaviors yet, which still do not match the design in full

Update draft documents storage to use new SQLite schema

---

build.gradle

Update android studio build tools.

Update android studio build tools

---

sdk/appcenter-identity/build.gradle

0.2.2 latest snapshot have fixed the timezone parsing issue so we need to upgrade again to use Facebook login.

Restore identity 0.2.2

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/BaseOptions.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

add the implementation of create or update just for diff

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/BaseOptions.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/ReadOptions.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java

Refactoring - moving isExpired method from BaseOptions to ReadOptions

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/StorageHttpClientDecorator.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Renamed `offlineMode` to `setOfflineModeEnabled` and `isOfflineModeEnabled`

Rename `offlineMode` to `setOfflineModeEnabled` and `isOfflineModeEnabled`

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java

Simplify a parameter in Storage that only used once. No functional change.

Simplify a parameter in Storage that only used once

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/context/AuthTokenContextAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AbstractAppCenterTest.java

Fix auth context initialization without identity module

Fix auth context initialization without identity module

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppStoreDetectionTest.java

In-app updates don't work on Samsung S8 and S9

Add samsung installer to local stores

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java

Code cleanup in storage that is preventing from making other PRs without warnings.

Code cleanup in storage

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java

Fix starting new services (identity shouldn't be started separately)
[AB#59535](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=59535)

Fix starting new services (identity shouldn't be started separately)

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/context/AuthTokenContext.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/context/AuthTokenContextTest.java

This is caused by listeners + synchronized.
We should run listeners after synchronizing, not during.
[AB#59457](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=59457)

Fix deadlock with push sending log and update token callback

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/channel/DefaultChannelTest.java

Fix sending logs after refreshing
[AB#59543](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=59543)

Fix sending logs after refreshing

---

sdk/appcenter-identity/src/main/java/com/microsoft/appcenter/identity/Identity.java
sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java

Wait token to expire (can modify expiration in code to avoid waiting 1 hour)
Track event and cause sign in refresh to fail or cancel (can simulate failure by modifying code as it will likely succeed most of the time).
=> Channel blocked.
Expected behavior: unblock channel sending and send logs anonymously.

Clear token on error and cancel actions

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/PendingOperation.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/NetworkStateChangeStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

SQLite android tests for subsequent offline operations

SQLite android tests for subsequent offline operations

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/TokenManager.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/TokenTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/UtilsTest.java

Fix user id validation in SDK side

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/NetworkStateChangeStorageTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

Refactor  public methods used in  to support overloads with  name parameter and fix corresponding usages

Refactor  public methods used in  to support overloads with  name parameter and fix corresponding usages

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java

Rename user partition to accommodate latest Token Exchange service

---

sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/568/
[AB#59615](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=59615)

Catch all exceptions from reading throwable

---

sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/DatabaseManagerTest.java

Add `create` and `drop` table operations to `DatabaseManager`

Handle multiple tables in DatabaseManager (creation and deletion)

---

sdk/appcenter-identity/src/test/java/com/microsoft/appcenter/identity/IdentityTest.java

Fix identity unit tests

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/Document.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Fix the offline read scenario 

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/SasquatchConstants.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/AppDocumentDetailActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/StorageActivity.java

Code cleanup missed during review of [AB#58933](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=58933)

Code cleanup missed during review of AB#58933

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java

Address https://github.com/Microsoft/AppCenter-SDK-Android/pull/1064

Fix incorrect writeOptions apply

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/TokenManager.java

Remove warning of token not found if token is found...
[AB#60022](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=60022)

Fix logging on TokenManager

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/TokenManager.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AuthTokenTests.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/TokenTest.java

Use prefix for Token storage preferences like in every module. To avoid collisions.
[AB#60030](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=60030)

Use prefix for Token storage

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Constants.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/TokenManager.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AuthTokenTests.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/TokenTest.java

Data tokens are stored in plain text

 Data tokens are stored in plain text

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java

A regression was introduced recently with post block being removed.

Fix strict mode for storage again

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/StorageActivity.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientRetryer.java

* Fix Android Studio warnings in HttpClientRetryer.
* FIx javac warnings in storage.

Fix some warnings

---

sdk/appcenter-identity/build.gradle

Revert MSAL dependency to 0.2.1

---

sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/UtilsTest.java

Fix conditions when delete is made online.
Introduces template method to share code between operations in similar effort (but not quite) as https://github.com/Microsoft/AppCenter-SDK-Apple/pull/1501.
[AB#60068](https://msmobilecenter.visualstudio.com/web/wi.aspx?pcguid=27bf89de-9697-418a-accf-1aa125b22914&id=60068)

Fix conditions when delete is made online

---

CHANGELOG.md
versions.gradle

Bump version to 2.0.0
Was already done in iOS

Bump version to 2.0.0

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/NewUserDocumentActivity.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/BaseOptions.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/ReadOptions.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/WriteOptions.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java

Fix some coding conventions

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/DocumentDetailActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/NewUserDocumentActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/StorageActivity.java
sdk/appcenter-storage/src/androidTest/java/com/microsoft/appcenter/storage/LocalDocumentStorageAndroidTest.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/LocalDocumentStorage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/TokenManager.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Utils.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/Document.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/DocumentError.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/DocumentMetadata.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/Page.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/PaginatedDocuments.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/PendingOperation.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/TokenResult.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/models/TokensResponse.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/LocalDocumentStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/NetworkStateChangeStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/TokenResultTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/TokenTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/UtilsTest.java

* Fix conventions for object naming.
* Just use Gson for date parsing in token.

Fix conventions for object naming / use gson for expiry date parsing

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/TokenManager.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/TokenExchange.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Fix crash when parsing invalid JSON for tokens.

Fix crash when parsing invalid JSON for tokens

---

sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/client/CosmosDb.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/AbstractStorageTest.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Remove the additional upsert header when it is create operation

Remove the additional upsert header when it is create operation

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/DocumentDetailActivity.java

Storage enable/disable option and a fix for time display.

More Storage UI on Sasquatch

---

sdk/appcenter-identity/build.gradle

Update msal to 0.3.1-RC2

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/StorageActivity.java
sdk/appcenter-storage/src/main/java/com/microsoft/appcenter/storage/Storage.java
sdk/appcenter-storage/src/test/java/com/microsoft/appcenter/storage/StorageTest.java

Add postAsyncGetter to the List call

---

sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Constants.java

Identity -> auth for file path on storage.

Rebrand local file path for auth config

---

sdk/appcenter-data/src/androidTest/java/com/microsoft/appcenter/data/LocalDocumentStorageAndroidTest.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/LocalDocumentStorageTest.java

Delete was missing the WriteOption as per the wiki page 
https://msmobilecenter.visualstudio.com/Mobile-Center/_wiki/wikis/Mobile-Center.wiki?wikiVersion=GBwikiMaster&pagePath=/Home/Teams/MBaaS/Data/Specifications/Java%20SDK%20Signatures&pageId=1925

Add writeoptions to Delete api

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

Storage.list must return an immediate error if no network

[Android] Storage.list must return an immediate error if no network

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

isFromCache not displaying the correct value for delete

isFromCache not displaying the correct value for delete

---

build.gradle
scripts/put-msal-repo-secrets-gradle.sh
sdk/appcenter-auth/build.gradle
sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java
sdk/appcenter-auth/src/test/java/com/microsoft/appcenter/auth/AuthTest.java

Use latest public msal library.
Remove private repo.

 Use latest public msal library

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/DataActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/DocumentDetailActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/NewUserDocumentActivity.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

Sync the signatures with the specs once again.

Re-order parameters on public signatures

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/PaginatedDocuments.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

Iterator.hasNext() throws null exception on empty list results

Iterator.hasNext() throws null exception on empty list results

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/LocalDocumentStorageTest.java

Fix comments

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClient.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClientCallTask.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/DefaultHttpClientTest.java

Disable http compression for Data.

Implement tests and functionality for pending operation processing

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClient.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpClientDecorator.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/HttpUtilsTest.java

Fix disabling compression for data

Fix disabling compression for data

---

sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java

Remove unnecessary suppressed warnings.

Remove unnecessary SuppressWarnings

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/TokenManager.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/DocumentWrapper.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClientCallTask.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/http/HttpUtilsTest.java

Fix javadoc warnings and improve it for Data

Fix javadoc warnings and improve it for Data

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/LocalDocumentStorageTest.java

Android bundle: replace offline should set offline flag + delete should set metadata on DocumentWrapper

Android bundle: replace offline should set offline flag + delete should set metadata on DocumentWrapper

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/exception/DataException.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/DocumentWrapper.java

Replace Throwable with Exception

Replace Throwable with Exception

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/UtilsTest.java

The Data SDK crashes if calling APIs without start

The Data SDK crashes if calling APIs without start

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/DocumentDetailActivity.java
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/data/AppDocumentListAdapter.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/LocalDocumentStorage.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Utils.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/DocumentMetadata.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/DocumentWrapper.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/PendingOperation.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/AbstractDataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/LocalDocumentStorageTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/NetworkStateChangeDataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/UtilsTest.java

Store only the user document JSON instead of full JSON

Store only the user document JSON instead of full JSON

---

CHANGELOG.md
README.md

Updating readme and changelog

---

CHANGELOG.md
README.md

Fix description for app center auth

---

CHANGELOG.md

Document accountId and userId changes

Document accountId and userId changes

---

CHANGELOG.md
README.md

Update auth description in readme and changelog.

Update auth description

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/NewUserDocumentActivity.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

If document ID is invalid, data operations will fail fast.

Fail fast if document id is empty string

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/TokenManager.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Utils.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/client/CosmosDb.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/client/TokenExchange.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/TokenTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/UtilsTest.java

Remove TODO

---

sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTarget.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTransmissionTargetTest.java

1. Added pauseGroup and resumeGroup for the analytics critical.
2. Update tests
[AB#61308](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61308)

Fixed missed the points in group-state-for-critical-events branch

---

CHANGELOG.md
sdk/appcenter-auth/proguard-rules.pro

Fix proguard rules for Auth module.
[AB#61143](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61143)

Fix proguard rules for Auth module

---

sdk/appcenter-data/proguard-rules.pro

Clean up unused Proguard rules in Data

Clean up unused Proguard rules in Data

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeAfterDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeDownloadTest.java

Fix NPE in distribution
#1141
[AB#61358](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61358)

Fix NPE in distribution

---

.gitmodules
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
README.md
publish.gradle

Rebrand github urls

---

scripts/run-code-coverage.sh

VM images have been updated, need to use both another image and another executable.

Fix emulator on CI

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/env.xml
apps/sasquatch/src/projectDependency/res/values/env.xml
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java

Fix log url after changing start type.

Fix log url after changing start type

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/ActivityConstants.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/layout/activity_event.xml
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/values/strings.xml
apps/sasquatch/src/main/res/xml/settings.xml

Add UI to Sasquatch app to set transmission interval when it sends event logs
[AB#59983](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/59983)

Added ui to set transmission interval

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
versions.gradle

Add UI/changelog for Distribute.setEnabledForDebuggableBuild.
#1011
[AB#61902](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61902)

Add UI/changelog for Distribute.setEnabledForDebuggableBuild

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java
versions.gradle

Merge the full feature branch for Distribute.setEnabledForDebuggableBuild.
Everything been reviewed before: #1011 #1160 
[AB#61902](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61902)

Merge the full feature branch for Distribute.setEnabledForDebuggableBuild

---

sdk/appcenter-data/src/androidTest/java/com/microsoft/appcenter/data/LocalDocumentStorageAndroidTest.java

Added a unit test to create and update offline documents with different IDs.

Add test: createAndUpdateOfflineDifferentIDs

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/channel/DefaultChannel.java

Don't send 50 logs immediately if transmission interval is custom
[AB#61886](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/61886)

Batching on custom interval

---

sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

There was an iOS bug with encoding double quotation marks in the documentId. Added a unit test to confirm Android did not contain the same bug.
[AB#62563](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/62563)

Added unit test

---

apps/sasquatch/src/main/AndroidManifest.xml
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/SasquatchConstants.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/DeviceInfoActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/DocumentDetailActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/UserInformationActivity.java
apps/sasquatch/src/main/res/layout/activity_user_information.xml
apps/sasquatch/src/main/res/values/strings.xml

[AB#62367](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/62367)

User info UI

---

CHANGELOG.md

Document the breaking change on UserInformation
[AB#62891](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/62891)

Document the breaking change on UserInformation

---

apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java
sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/UserInformation.java

Fix 2 warnings

---

CHANGELOG.md

Removed watermark(Under active development)

Removed watermark from CHANGELOG.md file

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml

Set the value of userid is null when userid is empty string

Fix the issue: cannot clear userid

---

sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

Add an override to `List` that takes a `ReadOptions`
[AB#63089](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/63089)

Add ReadOptions override to list operation

---

sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/AbstractDataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/AuthTokenTests.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataCreateUpdateDeleteTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataListTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataReadTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java

A follow up to comments in https://github.com/microsoft/appcenter-sdk-android/pull/1195

Previous PR follow up

---

CHANGELOG.md
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/TimeToLive.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/BaseOptions.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/AbstractDataTest.java

https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/63664

change default ttl to INFINITE

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/DataActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/data/AppDocumentListAdapter.java

For parity with the iOS test app. 
1) Click into a document. Make changes to the document in cosmosDB. Refresh the document to the new values.
2) Click back to the list
3) Click back to the document. It will show the original un-refreshed values.

[Android Test App] After refreshing a document, save the new document values in the list display

---

CHANGELOG.md
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/ReadOptions.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/models/WriteOptions.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataCreateUpdateDeleteTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataReadTest.java

Read and write options now accept null.

read write options accept null

---

CHANGELOG.md

Android SDK release - Version 2.2.0 - July

---

CHANGELOG.md
apps/sasquatch/build.gradle
versions.gradle

Start version 2.2.1

---

sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

Add the handle the memory warning event and save the info.
[AB#65505](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/65505)

Handle the memory warning event and save the info

---

apps/sasquatch/src/main/cpp/main.cpp
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/CrashActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/features/TestFeatures.java
apps/sasquatch/src/main/res/values/crashes.xml
apps/sasquatch/src/main/res/values/strings.xml

1. UI button to generate OOM warning
2. UI tile to display OOM warning
[AB#65510](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/65510)

Added UI for OOM

---

apps/sasquatch/src/main/cpp/main.cpp

Fix low memory warning in release mode.

[Fix] Low memory warning in release mode

---

CHANGELOG.md
sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/Push.java

Fix incorrect firebase logs' order.
[AB#65958](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/65958)

Fix firebase logs' order

---

sdk/appcenter-auth/src/main/java/com/microsoft/appcenter/auth/Auth.java

Change error level to warn when it failed to add a logger callback for MSAL.
[AB#65915](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/65915)

Downgrade error message to warn when it failed to set a logger in MSAL

---

CHANGELOG.md
versions.gradle

Android SDK release - Version 2.3.0 - August

---

versions.gradle

App Center has no issue running with this API level, more tests are being done before next release.

Use API level 29 in repo, it works

---

CHANGELOG.md

setRemoteOperationListener is not documented

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AuthTokenCallback.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AuthTokenListener.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterAuthTest.java

Rename `AuthProvider` to `AuthTokenListener` and rename/move `Callback` class

AuthProvider -> AuthTokenListener

---

sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/JwtClaimsTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/JwtClaims.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/AppCenterAuthTest.java

Add AppCenter.setAuthToken
[AB#67952](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/67952)

BYOI setAuthToken

---

sdk/appcenter-data/src/androidTest/java/com/microsoft/appcenter/data/LocalDocumentStorageAndroidTest.java

Fixed the flakey test.  We are no longer comparing time which was causing the issue.

Fix flakey test

---

apps/sasquatch/build.gradle
apps/sasquatch/src/jcenterDependency/java/com/microsoft/appcenter/sasquatch/activities/BYOIUtils.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/UserInformationActivity.java
apps/sasquatch/src/main/res/values/array.xml
apps/sasquatch/src/main/res/values/env.xml
apps/sasquatch/src/projectDependency/java/com/microsoft/appcenter/sasquatch/activities/BYOIUtils.java
apps/sasquatch/src/projectDependency/res/values/env.xml
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Utils.java

Add Auth0 login to test app.
[AB#67958](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/67958)

Bring your own Auth0

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/JwtUtils.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/AuthenticationProviderActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/UserInformationActivity.java
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Utils.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/AbstractDataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataCreateUpdateDeleteTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataListTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataReadTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/UtilsTest.java

Update code to remove forbidden characters from sqlite table name.
[AB#67958](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/67958)
Was discussed with team.

Update code to remove forbidden characters from sqlite table name

---

CHANGELOG.md
sdk/appcenter-data/src/main/java/com/microsoft/appcenter/data/Data.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/AbstractDataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataCreateUpdateDeleteTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataListTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataReadTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/DataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/NetworkStateChangeDataTest.java
sdk/appcenter-data/src/test/java/com/microsoft/appcenter/data/TokenTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/DefaultHttpClientCallTask.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpUtils.java

Use separate HTTP clients for online and offline operations. This is to fail fast on online operations and still keep retrying on offline ones.

Use separate HTTP clients for online and offline operations

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/http/HttpConnectionCheckTask.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/http/HttpConnectionDownloadFileTask.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/http/HttpConnectionReleaseDownloader.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerRequestTask.java

- Fix resume installing
- Fix `PREFERENCE_KEY_DOWNLOADED_RELEASE_FILE` sync
- Apply changes from testing branch
[AB#69950](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/69950)

Finalize HTTP connection downloader implementation

---

CHANGELOG.md

update changelog as per Amanda's suggesion

---

CHANGELOG.md

Android SDK release - Version 2.4.0 - October

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDownloadListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/ReleaseDownloader.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/http/HttpConnectionReleaseDownloader.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerUpdateTask.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/ReleaseDownloadListenerTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/AppCenterLog.java

Fix crash on `null` error message
#1282 
[AB#71054](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/71054)

Fix crash on download update error

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerUpdateTask.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerUpdateTaskTest.java

This PR will add `COLUMM_REASON` of a cursor to error message when logging download fail message.
[AB#71184](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/71184)

Add reason to logging

---

CHANGELOG.md

Android SDK release - Version 2.4.1 - October

---

CHANGELOG.md
apps/sasquatch/build.gradle

Use new SDK in demo app to master

---

CHANGELOG.md
versions.gradle

Start version 2.4.2

---

sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManagerAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManager.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/HandledErrorTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManagerTest.java

Expose utilities for Unity SDK.
[AB#71515](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/71515)

Handled ErrorReport for wrapper SDKs

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/CrashTestHelper.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/CrashActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/CrashSubActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/ManagedErrorActivity.java
apps/sasquatch/src/main/res/layout/activity_log_top.xml
apps/sasquatch/src/main/res/values/crashes.xml
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/WrapperSdkExceptionManager.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/AbstractCrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/HandledErrorTest.java

Add attachments to handled errors.
[AB#71068](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/71068)

Handled error attachments

---

apps/sasquatch/build.gradle

Use new SDK 2.4.2 in demo app

---

CHANGELOG.md

Android SDK release - Version 2.5.0 - November

---

apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/ManagedErrorActivity.java

Use new SDK v2.5.0 in demo app

---

sdk/appcenter/src/test/java/com/microsoft/appcenter/DependencyConfigurationTest.java

Make dependency tests more reliable when executed with other tests

---

CHANGELOG.md

Android SDK release - Version 2.5.1 - December

---

apps/sasquatch/build.gradle

Use new SDK v2.5.1 in demo app

---

CHANGELOG.md
apps/sasquatch/build.gradle
versions.gradle

Start version 2.5.2

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java

[AB#74714](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/74714)

Add DependencyConfiguration for Distribute http client

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
scripts/run-code-coverage.sh

A rule is now enforced somehow without code changes (probably android tools update on azure pipelines).

Fix builds

---

README.md

Fix badge on readme

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeConstants.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/DistributeUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeApiSuccessTest.java

Android uses the new endpoints for public/private
[AB#75579](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/75579)

Use new endpoints for private setup, public in-app updates

---

CHANGELOG.md

[AB#75278](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/75278)

In app updates changelog

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java

remove unused variable

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeManualCheckForUpdateTest.java

Manual check for update API.
[AB#75293](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/75293)

Implement Distribute.checkForUpdate

---

CHANGELOG.md

Android SDK release - Version 3.0.0 - January

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java

Add UI to check for updates manually in test app
[AB#75364](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/75364) part 2

Add UI to check for updates manually in test app

---

CHANGELOG.md
versions.gradle

Android SDK release - Version 3.1.0 - March

---

apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/features/TestFeatures.java

Use new SDK v3.1.0 in demo app

---

scripts/publish-github-release.sh

Things to consider before you submit the PR:
GitHub deprecates API authentication through query parameters.
Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/ for more information
[AB#77883](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/77883)

Pass token as a header instead of query parameter

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AbstractDistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
versions.gradle

Add tryResetWorkflow() call in the Distribute class.
[AB#78294](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/78294)

Check in-app updates on resume

---

apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml

[AB#76737](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/76737)

Fix radio buttons not getting default values

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/MSAAuthenticationProvider.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/EventActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MSALoginActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java

Persist MSA UserId
[AB#76752](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/76752)

Stay logged in to MSA after app restart

---

apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml

Reorganize some code and resources related to that setting.
Fix toast message in distribute auto check for update.

Fix toast message in distribute auto check for update

---

cgmanifest.json

Cgmanifest.json added.
[AB#77893](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/77893)

Add Component Governance manifest

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/MSAAuthenticationProvider.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MSALoginActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
cgmanifest.json
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/FileManager.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/FileManagerTest.java

Develop branch was merged into the current branch and cgmanifest file was updated (lifecycle-process info was added).
https://github.com/microsoft/appcenter-sdk-android/pull/1392
[AB#73043](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/73043)

Merge changes from develop and fix Component Governance manifest

---

cgmanifest.json

Information about breakpad was fixed in cgmanifest.
https://github.com/microsoft/appcenter-sdk-android/pull/1399
[AB#77893](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/77893)

Breakpad info corrected in cgmanifest

---

CHANGELOG.md

Android SDK release - Version 3.2.0 - April

---

apps/sasquatch/build.gradle

Use new SDK v3.2.0 in demo app

---

CHANGELOG.md
versions.gradle

Start new version 3.2.1

---

CHANGELOG.md

Android SDK release - Version 3.2.1 - April

---

apps/sasquatch/build.gradle

Use new SDK v3.2.1 in demo app

---

CHANGELOG.md
versions.gradle

Start new version 3.2.2

---

CHANGELOG.md

Android SDK release - Version 3.2.2 - June

---

apps/sasquatch/build.gradle

Use new SDK v3.2.2 in demo app

---

CHANGELOG.md
versions.gradle

Start new version 3.2.3

---

CHANGELOG.md
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/persistence/DatabasePersistenceAndroidTest.java
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/utils/storage/DatabaseManagerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/persistence/DatabasePersistence.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/SQLiteUtils.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/storage/DatabaseManagerTest.java

Add a hardcoded SQLite request for creating an SQL table.
[AB#81470](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/81470)

Refactor SQLite tables creation to avoid SQL injections 

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppStoreDetectionTest.java

For several devices were a possible situation when the package installer name could not be found in the locale stores.
[AB#82014](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/82014)
microsoft/appcenter-sdk-dotnet#1418

Local stores updated

---

CHANGELOG.md
versions.gradle

Android SDK release - Version 3.3.0 - July

---

apps/sasquatch/build.gradle

Use new SDK v3.3.0 in demo app

---

apps/build.gradle

Fix path to copy apk in the build script

Fix path to copy apk

---

.gitignore
build.gradle
gradle/wrapper/gradle-wrapper.properties
versions.gradle

Update Android Studio plugin and Gradle to keep it up to date and probably detect some new issues with new API like deprecations and so on
[AB#82284](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/82284)

Update Android tools and Gradle

---

apps/appcenter-post-clone.sh

~* [ ] Has `CHANGELOG.md` been updated?~
~* [ ] Are tests passing locally?~
~* [ ] Did you add unit tests?~
~* [ ] Did you check UI tests on the sample app? They are not executed on CI.~
Fix App Center build for Android 11.

Add set ndk script to post clone

---

CHANGELOG.md

#1453
[AB#82515](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/82515)

Add more specific link to docs

---

README.md

Google can consider in-app update code as malicious behavior even if it isn't used at runtime. We recommend you to strip this code from your application before submitting it to Google Play.
[AB#82605](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/82605)

Update readme about distribute

---

CHANGELOG.md

Android SDK release - Version 3.3.1 - September

---

apps/sasquatch/build.gradle

Use new SDK V3.3.1 in demo app

---

apps/sasquatch/src/main/AndroidManifest.xml
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MSALoginActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
versions.gradle

- Remove 4.x dependencies from test application
- Update sdk version in Gradle
[AB#83679](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/83679)

Update test applications and update version in gradle

---

CHANGELOG.md

Android SDK release - Version 4.0.0 - November

---

apps/sasquatch/build.gradle

Use new SDK V4.0.0 in demo app

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java

~~* [ ] Did you add unit tests?~~ (This is a bug fix)
[AB#83811](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/83811)

Add check that activity is not null before opening settings screen

---

CHANGELOG.md
versions.gradle

Android SDK release - Version 4.1.0 - December

---

apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchDistributeListener.java

Use new SDK V4.1.0 in demo app.

---

CHANGELOG.md
apps/sasquatch/src/androidTest/java/com/microsoft/appcenter/sasquatch/activities/CrashesTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

Fix build Sasquatch UI tests
[AB#84103](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/84103)

Fix Sasquatch UI tests and stack trace formatting

---

CHANGELOG.md
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/CrashesAndroidTest.java
sdk/appcenter-crashes/src/androidTest/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperAndroidTest.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelper.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/utils/ErrorLogHelperTest.java

[AB#84406](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/84406)

Fix missing User ID in NDK reports

---

.github/workflows/codeql.yml
apps/appcenter-post-clone.sh
apps/sasquatch/build.gradle
build.gradle
scripts/put-azure-credentials.sh

[AB#85171](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/85171)

Update the release process (feedback)

---

CHANGELOG.md

Android SDK release - Version 4.1.1 - March

---

apps/sasquatch/build.gradle

Use new SDK V4.1.1 in demo app

---

scripts/publish-storage-account.sh

[AB#85778](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/85778)

Fix publishing artifacts to storage account

---

apps/sasquatch/build.gradle
sdk/build.gradle
versions.gradle

[AB#86509](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/86509)

[Android 12] Fix SDK build

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDownloadListener.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/ReleaseDownloadListenerTest.java

[AB#86507](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/86507)

[Android 12] Distribute module

---

CHANGELOG.md
apps/sasquatch/build.gradle
apps/sasquatch/src/main/AndroidManifest.xml
sdk/appcenter-distribute/src/main/AndroidManifest.xml
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDownloadListener.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/ReleaseDownloadListenerTest.java
versions.gradle

[AB#86509](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/86509)

Fix compatibility SDK with Android 12

---

apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java

Use new SDK V4.2.0 in demo app

---

.github/workflows/codeql.yml
gradle.properties
scripts/add-gradle-property.sh

* ~[ ] Has `CHANGELOG.md` been updated?~
* ~[ ] Are tests passing locally?~
* ~[ ] Are the files formatted correctly?~
* ~[ ] Did you add unit tests?~
* ~[ ] Did you check UI tests on the sample app? They are not executed on CI.~
This PR adds file gradle.properties with required properties for building the project:
```
android.useAndroidX=true
android.enableJetifier=true
```

Add gradle.properties file

---

apps/sasquatch/build.gradle
versions.gradle

Downgrade Android SDK version in Demo app.

Downgrade Android SDK version in Demo app

---

scripts/publish-storage-account.sh

[AB#87051](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/87051)

[CI] Fix versioning for dev releases

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppStoreDetectionTest.java

* ~[ ] Did you check UI tests on the sample app? They are not executed on CI.~
Add `Distribute.addStores(stores)` API for adding stores.
[AB#87875](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/87875)

Add new API for adding local stores

---

CHANGELOG.md
scripts/publish-storage-account.sh
versions.gradle

Fix uploading artifacts

---

apps/sasquatch/build.gradle

Use new SDK V4.3.1 in demo app

---

scripts/publish-storage-account.sh

Fix publishing snapshot version.
[AB#88966](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/88966)

Fix publishing snapshot version

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/res/values/settings.xml
apps/sasquatch/src/main/res/xml/settings.xml
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/channel/SessionTracker.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/AnalyticsTest.java
sdk/appcenter-analytics/src/test/java/com/microsoft/appcenter/analytics/channel/SessionTrackerTest.java

Add the ability to control the start of a session manually
[AB#88923](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/88923)

Add the ability to control the start of a session manually

---

CHANGELOG.md
sdk/appcenter-analytics/src/main/java/com/microsoft/appcenter/analytics/Analytics.java

Increase the interval between sending logs.
[AB#89231](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89231)

Increase the interval between sending logs

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/AppCenterPackageInstallerReceiver.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseDownloadListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/ReleaseInstallerListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/ReleaseDownloader.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerReleaseDownloader.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerUpdateTask.java
sdk/appcenter-distribute/src/main/res/values/appcenter_distribute.xml
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeWarnAlertSystemWindowsTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/ReleaseDownloadListenerTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/ReleaseInstallerListenerTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerDistributeDeadlockTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerReleaseDownloaderTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/download/manager/DownloadManagerUpdateTaskTest.java

Add sumcheck on the downloaded file before starting the install process.
[AB#89236](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89236)

Add check for downloaded file

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/AppCenterLog.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/AppCenterLogTest.java

Add setLogger API.
[AB#89363](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89363)

Add setLogger API

---

sdk/appcenter-distribute/src/main/AndroidManifest.xml

Fix distribute manifest

---

apps/sasquatch/build.gradle
apps/sasquatch/src/androidTest/java/com/microsoft/appcenter/sasquatch/activities/AnalyticsTest.java
apps/sasquatch/src/androidTest/java/com/microsoft/appcenter/sasquatch/activities/utils/EspressoUtils.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/analytics/AnalyticsPrivateHelper.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java

Use new SDK V4.4.0 in demo app

---

apps/sasquatch/build.gradle

Use new SDK V4.4.1 in demo app

---

CHANGELOG.md
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/AppCenterPackageInstallerReceiver.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/AppCenterPackageInstallerReceiverTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/InstallerUtilsTest.java
versions.gradle

[AB#89701](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89701)
#1587

Fix missing required flag on Android 31 API

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/AppCenterLog.java
sdk/appcenter/src/test/java/com/microsoft/appcenter/utils/AppCenterLogTest.java

Revert assert logs.
[AB#89684](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89684)

Revert assert logs

---

CHANGELOG.md
sdk/appcenter/src/androidTest/java/com/microsoft/appcenter/ingestion/models/json/LogSerializerAndroidTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/models/StartServiceLog.java

Fix parsing startServiceLog.
[AB#89670](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89670)
#1584

Fix parsing startServiceLog

---

apps/sasquatch/build.gradle
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/MainActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/activities/SettingsActivity.java
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/util/EventActivityUtil.java
apps/sasquatch/src/main/res/values/env.xml
apps/sasquatch/src/main/res/values/targets.xml
apps/sasquatch/src/main/res/xml/settings.xml
apps/sasquatch/src/projectDependency/res/values/env.xml
apps/sasquatch/src/projectDependency/res/values/targets.xml

Remove app-secret values from demo apps.
[AB#89921](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/89921)

Remove app-secret values from demo apps

---

CHANGELOG.md
sdk/appcenter-distribute-play/src/main/java/com/microsoft/appcenter/distribute/Distribute.java

[AB#91186](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/91186)

Add missing Distribute.addStores API

---

CHANGELOG.md
sdk/appcenter-crashes/src/main/java/com/microsoft/appcenter/crashes/Crashes.java
sdk/appcenter-crashes/src/test/java/com/microsoft/appcenter/crashes/CrashesTest.java

[#2382](https://github.com/microsoft/appcenter/issues/2382/)
[AB#91298](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/91298)

Add null check for AppCenter.trackError

---

CHANGELOG.md
apps/sasquatch/src/main/java/com/microsoft/appcenter/sasquatch/listeners/SasquatchDistributeListener.java
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeCustomizationTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java

[AB#91473](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/91473)
#1604

Fix show in-app update dialog

---

CHANGELOG.md

[AB#93490](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/93490)

Android SDK release - Version 4.4.4

---

apps/sasquatch/build.gradle

[AB#93490](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/93490)

Use new SDK V4.4.4 in demo app

---

CHANGELOG.md

[AB#93655](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/93655)

Android SDK release - Version 4.4.5

---

apps/sasquatch/build.gradle

[AB#93655](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/93655)

Use new SDK V4.4.5 in demo app

---

CHANGELOG.md
versions.gradle

[AB#93655](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/93655)

Start version 4.4.6

---

CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/http/HttpUtils.java

- Fixing code scanning alert ["Polynomial regular expression used on uncontrolled data"](https://github.com/microsoft/appcenter-sdk-android/security/code-scanning/2)
- Adding paragraph App Center Distribute to CHANGELOG.md

Polishing release 5.0.0

---

CHANGELOG.md
build.gradle
sdk/build.gradle

Migrating from maven dcedent to maven publish.
[AB#92370](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/92370)

Migrate maven publish

---

CHANGELOG.md

Android SDK release - Version 5.0.1

---

sdk/build.gradle

This PR fixes maven publication task, including adding proper artifacts and correcting the pom file.
[AB#100272](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/100272)

Fix maven publishing and pom file generation

---

sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/install/session/SessionReleaseInstaller.java

Added logging about update cancellation due to lack of progress.
#1680

Add logging about update cancellation due to lack of progress

---

publish.gradle
scripts/put-bintray-secrets-gradle.sh
sdk/build.gradle

This PR fix CI issues while migrating from Maven-release to ESRP-task release. 
[AB#103322 ](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/SDK/Backlog%20Items/?workitem=103322)

[CI] Migrate Maven-Release to ESRP-Release task

---

apps/sasquatch/src/projectDependency/res/values/env.xml

Replace old int env variables since they were no longer used

Update int env to pme

---

.azurepipelines/publish-maven-1ES.yml

Enable ESRP task in order to publish sdk release

Enable ESRP task

---

.azurepipelines/publish-maven-1ES.yml
apps/sasquatch/src/projectDependency/res/values/env.xml

Enable ESRP Release task
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1539133&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=2840af88-fe4e-50c7-e711-ba2fef0ab96b)

Enable ESRP Release task

---

.azurepipelines/publish-maven-1ES.yml

Removed scanning of languages ​​that are not being built during the version information collection stage.
[Build succeed](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1540438&view=results)
[AB#107387](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/107387)

Fix CodeQL scan

---

sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

Close cursor after deleting old records.
[AB#107569](https://dev.azure.com/msmobilecenter/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/107569)

Fix close cursor

---

.azurepipelines/publish-maven-1ES.yml

- Extract version info.
- Remove ESRP release task (moved to release pipeline)
[#AB107443](https://dev.azure.com/msmobilecenter/Mobile-Center/_boards/board/t/Mobile%20SDK%20team/Backlog%20Items/?workitem=107443)
[Build](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1542540&view=results)

[CI] Add file with version to build artifacts

---

.azurepipelines/publish-maven-1ES.yml
CHANGELOG.md
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java

Version 5.0.5 additional changes

---

CHANGELOG.md
versions.gradle

Update gradle.version and contribution.md for starting next version

Start new 5.0.6 version

---

CHANGELOG.md
apps/sasquatch/build.gradle

* **[Fix]** [Fix app crash on hiding install update dialog.](https://github.com/microsoft/appcenter-sdk-android/pull/1750)
[Build succeed](https://dev.azure.com/msmobilecenter/SDK/_build/results?buildId=1552357&view=results)

Release 5.0.6 version

---

.azurepipelines/azure-maven-template.yml
.azurepipelines/build-demo-app.yml
.azurepipelines/publish-maven-1ES.yml
CHANGELOG.md
apps/sasquatch/build.gradle
scripts/run-code-coverage.sh
sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeBeforeDownloadTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeTest.java
sdk/appcenter-distribute/src/test/java/com/microsoft/appcenter/distribute/DistributeWarnUnknownSourcesTest.java
sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/storage/DatabaseManager.java
versions.gradle

[Fix] Dismiss dialog instead of hiding it #1750

Version 5.0.6
